"""Test data for {{TC_NUMBER_CANONICAL}} — generated by tcrt-automation-init.

Output path: fixtures/test_data.py   (TCRT excludes fixtures/ from smart-scan)

Values come from the test case's ``test_data`` array (TCRT MCP). Mapping rules:

  * Non-secret categories (text / number / email / url / identifier / date /
    json) are inlined into ``DATA`` as literals.
  * ``credential`` category values are NEVER inlined — they are read from
    environment variables so secrets stay out of git. Export them before the
    run. (TCRT's MCP returns the real value, but audit logs redact it; do not
    paste it into source.)
"""
from __future__ import annotations

import os

# Non-secret test data. Key = test_data[i].name, value = test_data[i].value.
DATA: dict[str, str] = {
    # "email": "qa@example.com",            # TODO(init): category=email
    # "target_url": "https://app/login",    # TODO(init): category=url
    # "order_id": "ORD-1001",               # TODO(init): category=identifier
}

# Credentials (category=credential) — kept OUT of source. Set via env vars.
SECRETS: dict[str, str] = {
    # "password": os.environ["TC_PASSWORD"],  # TODO(init): export TC_PASSWORD
}
