"""{{PAGE_CLASS}} — page object STUB generated by tcrt-automation-init.

Output path: pages/{{PAGE_MODULE}}.py

This stub was inferred from the test case STEPS — one page object per page
surface the steps touch. Fill in:

  * ``path``                  — the route this page lives at (e.g. "/login")
  * locators (in __init__)    — one per element a step interacts with
  * action methods            — one per step verb (fill / click / select ...)

Contract (keep it — see references/testcase-to-skeleton.md):
  * constructor takes ``page``; never instantiates its own.
  * locators are instance attributes created once in __init__.
  * action methods mutate page state and return None or the NEXT page object.
  * NO assertions here — assertions live in the test (expected_result).
  * NO time.sleep — use Playwright's auto-waiting / expect() in the test.
"""
from __future__ import annotations

from playwright.sync_api import Page

from .base_page import BasePage


class {{PAGE_CLASS}}(BasePage):
    path = "/"  # TODO(init): set the real route, e.g. "/login" — TCG Admin: the resolved menuId route, e.g. "/73050"

    def __init__(self, page: Page) -> None:
        super().__init__(page)
        # TODO(init): one locator per element the steps touch, e.g.
        # self.email_input = page.get_by_label("Email")
        # self.password_input = page.get_by_label("Password")
        # self.submit_button = page.get_by_role("button", name="Sign in")

    # TODO(init): one action method per step verb. Example shape:
    #
    # def login(self, email: str, password: str) -> None:
    #     self.email_input.fill(email)
    #     self.password_input.fill(password)
    #     self.submit_button.click()
