"""{{TC_TITLE}} — Playwright (sync) + pytest  ->  script_format: PYTEST

Generated by tcrt-automation-init.
Source:             TCRT MCP — team "{{TEAM}}", test case {{TC_NUMBER_CANONICAL}}
Generated:          {{TIMESTAMP_UTC}}
TCRT script_format: PYTEST   (filename starts with ``test_``)
Framework:          playwright (sync) + pytest

FILL-IN-THE-BLANK skeleton. Every step / expected result below is quoted
verbatim from the test case. Workflow:
  1. Flesh out pages/{{PAGE_MODULE}}.py (locators + action methods).
  2. Replace each ``TODO`` line here with a real page-object call / assertion.
  3. Delete the ``@pytest.mark.skip`` decorator.
  4. Run ``tcrt-automation-pomify`` to validate the POM contract + manifest.
"""
from __future__ import annotations

import pytest
from playwright.sync_api import Page, expect

from pages.{{PAGE_MODULE}} import {{PAGE_CLASS}}
from fixtures.test_data import DATA, SECRETS


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT
# (Settings → Environments / Script view → "Configure variables"). See SKILL.md §6.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


@pytest.mark.skip(reason="skeleton — implement the TODOs below, then remove this decorator")
@pytest.mark.tcrt("{{TC_NUMBER}}", link_type="{{LINK_TYPE}}")
def test_{{TEST_NAME}}(page: Page) -> None:
    # ───────────────────────────────────────────────────────────────────────
    # PRECONDITION (arrange):
    #   {{PRECONDITION}}
    # ───────────────────────────────────────────────────────────────────────
    {{PAGE_VAR}} = {{PAGE_CLASS}}(page)
    {{PAGE_VAR}}.goto()  # TODO(init): confirm this is the right entry point

    # ───────────────────────────────────────────────────────────────────────
    # STEPS (act):  one block per numbered step, quoted verbatim.
    # ───────────────────────────────────────────────────────────────────────
{{STEPS_BLOCK}}

    # ───────────────────────────────────────────────────────────────────────
    # EXPECTED RESULT (assert):  one assertion per expected outcome.
    # ───────────────────────────────────────────────────────────────────────
{{EXPECTED_BLOCK}}
