"""BasePage — shared helpers for Playwright (async) page objects.

Generated by tcrt-automation-init. Output path: pages/base_page.py
"""
from __future__ import annotations

from playwright.async_api import Page


class BasePage:
    path: str = "/"

    def __init__(self, page: Page) -> None:
        self.page = page

    async def goto(self) -> None:
        await self.page.goto(self.path)

    async def wait_for_path(self, path: str, timeout_ms: int = 10_000) -> None:
        await self.page.wait_for_url(f"**{path}", timeout=timeout_ms)
