"""{{PAGE_CLASS}} — page object STUB (async) generated by tcrt-automation-init.

Output path: pages/{{PAGE_MODULE}}.py

Inferred from the test case STEPS. Fill in ``path``, locators, and one async
action method per step verb. Contract: constructor takes ``page``; locators are
instance attrs; actions return None or the next page object; NO assertions here.
"""
from __future__ import annotations

from playwright.async_api import Page

from .base_page import BasePage


class {{PAGE_CLASS}}(BasePage):
    path = "/"  # TODO(init): set the real route, e.g. "/login" — TCG Admin: the resolved menuId route, e.g. "/73050"

    def __init__(self, page: Page) -> None:
        super().__init__(page)
        # TODO(init): one locator per element the steps touch, e.g.
        # self.email_input = page.get_by_label("Email")
        # self.submit_button = page.get_by_role("button", name="Sign in")

    # TODO(init): one async action method per step verb. Example shape:
    #
    # async def login(self, email: str, password: str) -> None:
    #     await self.email_input.fill(email)
    #     await self.password_input.fill(password)
    #     await self.submit_button.click()
