"""{{TC_TITLE}} — Playwright (async)  ->  script_format: PLAYWRIGHT_PY_ASYNC

Generated by tcrt-automation-init.
Source:             TCRT MCP — team "{{TEAM}}", test case {{TC_NUMBER_CANONICAL}}
Generated:          {{TIMESTAMP_UTC}}
TCRT script_format: PLAYWRIGHT_PY_ASYNC   (filename uses ``flow_`` prefix)
Framework:          playwright (async)

Filename starts with ``flow_`` (NOT ``test_``) so TCRT classifies it as
PLAYWRIGHT_PY_ASYNC. The manifest's ``scan.include`` MUST carry a ``flow_*.py``
glob or TCRT silently skips this file. The test FUNCTION still uses the
``test_`` prefix so smart-scan's AST walker extracts its name.

FILL-IN-THE-BLANK skeleton — see the sync template's header for the workflow.
"""
from __future__ import annotations

import pytest
from playwright.async_api import Page, expect

from pages.{{PAGE_MODULE}} import {{PAGE_CLASS}}
from fixtures.test_data import DATA, SECRETS


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT
# (Settings → Environments / Script view → "Configure variables"). See SKILL.md §6.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


@pytest.mark.skip(reason="skeleton — implement the TODOs below, then remove this decorator")
@pytest.mark.tcrt("{{TC_NUMBER}}", link_type="{{LINK_TYPE}}")
async def test_{{TEST_NAME}}(page: Page) -> None:
    # ───────────────────────────────────────────────────────────────────────
    # PRECONDITION (arrange):
    #   {{PRECONDITION}}
    # ───────────────────────────────────────────────────────────────────────
    {{PAGE_VAR}} = {{PAGE_CLASS}}(page)
    await {{PAGE_VAR}}.goto()  # TODO(init): confirm entry point

    # ───────────────────────────────────────────────────────────────────────
    # STEPS (act):  one block per numbered step, quoted verbatim.
    # ───────────────────────────────────────────────────────────────────────
{{STEPS_BLOCK}}

    # ───────────────────────────────────────────────────────────────────────
    # EXPECTED RESULT (assert):  one assertion per expected outcome.
    # ───────────────────────────────────────────────────────────────────────
{{EXPECTED_BLOCK}}
