"""{{COLLECTION_NAME}} - Postman collection converted to pytest API tests.

Generated by tcrt-automation-pomify.
Source:             {{SOURCE_PATH}}
Generated:          {{TIMESTAMP_UTC}}
TCRT script_format: PYTEST   (filename starts with ``test_``)
Framework:          pytest + httpx (converted from Postman; no browser driver)

Replace any TODO marker IDs and assertion gaps before enabling in a suite.
"""
from __future__ import annotations

import os

import httpx
import pytest


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT.
# See references/environment-config.md.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


API_BASE_URL = os.environ.get("API_BASE_URL", "{{BASE_URL}}")
DEFAULT_HEADERS: dict[str, str] = {{DEFAULT_HEADERS}}


{{TEST_FUNCTIONS}}
