"""conftest.py snippet — register the ``tcrt`` pytest marker.

Generated by tcrt-automation-pomify.
Output path: conftest.py (at repo root or tests/)

Merge this into your existing ``conftest.py``, or copy the file wholesale if
you don't have one yet. The ``pytest_configure`` hook registers the custom
``tcrt`` marker so pytest does NOT emit ``PytestUnknownMarkWarning`` when it
encounters ``@pytest.mark.tcrt(...)`` decorators in your test files.

TCRT smart-scan auto-excludes ``conftest.py`` from test discovery, so this
file is safe to place anywhere under your ``tests/`` tree or at the repo root.

It also logs the active TCRT automation environment at the top of each run (the
``pytest_report_header`` hook) — keep this even when the repo reads values via
the ``tcrt_env.py`` helper rather than the ``tcrt_env`` fixture.
"""
from __future__ import annotations

import json
from pathlib import Path


def pytest_configure(config: "pytest.Config") -> None:
    config.addinivalue_line(
        "markers",
        "tcrt(*tc_ids, link_type='covers'): declare TCRT manual test case coverage. "
        "tc_ids must match ^[A-Za-z0-9_-]+$. "
        "link_type must be one of: primary, covers, references.",
    )


def pytest_report_header(config: "pytest.Config"):
    """Log the active TCRT automation environment + resolved variables at the top
    of the run so it lands in the Jenkins console.

    Runs once per session (the environment is per-run). Uses the pytest session
    header — NOT a plain ``print``, which pytest captures and only shows for
    FAILED tests, so a green run would log nothing. Non-secret values are shown;
    secret values (declared ``secret: True``, listed in the bundle's
    ``__tcrt__.secret_keys``) are masked. Suppressed only under ``pytest -q``.
    ``tcrt-env.json`` sits at the run root (the Jenkins workspace); absent when
    no environment is selected, in which case this reports that plainly.
    """
    bundle_path = Path(str(config.rootpath)) / "tcrt-env.json"
    if not bundle_path.exists():
        return "TCRT automation environment: (none selected — tests use os.environ / defaults)"
    try:
        bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    except (ValueError, OSError):
        return "TCRT automation environment: (tcrt-env.json unreadable)"
    if not isinstance(bundle, dict):
        return "TCRT automation environment: (tcrt-env.json malformed)"
    meta = bundle.get("__tcrt__") if isinstance(bundle.get("__tcrt__"), dict) else {}
    env_name = (meta or {}).get("environment") or "(unknown)"
    secret_keys = set((meta or {}).get("secret_keys") or [])
    lines = [f"TCRT automation environment: {env_name}"]
    for ref_path, values in sorted(bundle.items()):
        if ref_path == "__tcrt__" or not isinstance(values, dict):
            continue
        rendered = ", ".join(
            f"{key}=***(secret)" if key in secret_keys else f"{key}={value}"
            for key, value in sorted(values.items())
        )
        lines.append(f"  {ref_path}: {rendered or '(no variables)'}")
    return lines
