"""Settings loader — ``tcrt_env`` pytest fixture. Generated by tcrt-automation-pomify.

Output path: conftest.py (at repo root or under tests/)

Merge the ``tcrt_env`` fixture below into your existing ``conftest.py`` (keep the
``tcrt`` marker registration too). TCRT smart-scan auto-excludes ``conftest.py``,
so this is never treated as a test.

What it does
------------
At run time TCRT injects the per-environment config as a single masked CI
parameter ``TCRT_ENV_BUNDLE``; the Jenkins suite job writes the non-empty bundle
to ``repo/tcrt-env.json`` (workspace, gitignored). ``tcrt-env.json`` is namespaced
per script by the script's repo-relative path (``ref_path``):

    { "tests/ui/test_login.py": {"BASE_URL": "…", "API_TOKEN": "…"}, ... }

This fixture reads that file, picks the namespace matching the CURRENT test
file's repo-relative path, and returns the variables by their fixed names. When
no environment is selected, ``tcrt-env.json`` is absent and the fixture falls
back to ``os.environ`` — tests with no ``TCRT_VARS`` are unaffected.

Usage in a test:

    def test_login(page, tcrt_env):
        base_url = tcrt_env["BASE_URL"]      # fixed name; value comes from TCRT
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest


def pytest_configure(config: "pytest.Config") -> None:
    config.addinivalue_line(
        "markers",
        "tcrt(*tc_ids, link_type='covers'): declare TCRT manual test case coverage. "
        "tc_ids must match ^[A-Za-z0-9_-]+$. "
        "link_type must be one of: primary, covers, references.",
    )


def _repo_root() -> Path:
    # tcrt-env.json is written to the repo root (the Jenkins workspace). This
    # conftest.py sits at the repo root or under tests/; walk up to find the file.
    here = Path(__file__).resolve()
    for parent in [here.parent, *here.parents]:
        if (parent / "tcrt-env.json").exists():
            return parent
    # Fall back to this file's directory (or its parent if under tests/).
    return here.parent.parent if here.parent.name == "tests" else here.parent


def _load_bundle() -> dict[str, dict[str, str]]:
    bundle_path = _repo_root() / "tcrt-env.json"
    if not bundle_path.exists():
        return {}
    try:
        data = json.loads(bundle_path.read_text(encoding="utf-8"))
    except (ValueError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def pytest_report_header(config: "pytest.Config"):
    """Log the active TCRT automation environment + resolved variables at the top
    of the run so it lands in the Jenkins console.

    Runs once per session (the environment is per-run, so per-test repetition
    would add no information). Uses the pytest session header — NOT a plain
    ``print``, which pytest captures and only shows for FAILED tests, so a green
    run would log nothing. Non-secret values are shown; secret values (declared
    ``secret: True``, listed in the bundle's ``__tcrt__.secret_keys``) are masked.
    Suppressed only under ``pytest -q``. When no environment is selected the
    bundle is absent and this reports that plainly.
    """
    bundle = _load_bundle()
    if not bundle:
        return "TCRT automation environment: (none selected — tests use os.environ / defaults)"
    meta = bundle.get("__tcrt__") if isinstance(bundle.get("__tcrt__"), dict) else {}
    env_name = (meta or {}).get("environment") or "(unknown)"
    secret_keys = set((meta or {}).get("secret_keys") or [])
    lines = [f"TCRT automation environment: {env_name}"]
    for ref_path, values in sorted(bundle.items()):
        if ref_path == "__tcrt__" or not isinstance(values, dict):
            continue
        rendered = ", ".join(
            f"{key}=***(secret)" if key in secret_keys else f"{key}={value}"
            for key, value in sorted(values.items())
        )
        lines.append(f"  {ref_path}: {rendered or '(no variables)'}")
    return lines


@pytest.fixture
def tcrt_env(request: "pytest.FixtureRequest") -> dict[str, str]:
    """Per-environment config for the current test file, keyed by fixed names.

    Resolves the namespace by the test file's repo-relative path (``ref_path``).
    Returns an empty dict (falling back to ``os.environ`` per-key) when no
    environment is selected and ``tcrt-env.json`` is absent.
    """
    bundle = _load_bundle()
    root = _repo_root()
    rel_path = Path(str(request.fspath)).resolve().relative_to(root).as_posix()
    values = dict(bundle.get(rel_path, {}))

    class _Env(dict):
        def __missing__(self, key: str) -> str:
            # Backward-compatible fallback when nothing was injected for this key.
            return os.environ[key]

    return _Env(values)
