"""Settings loader — ``tcrt_env.py`` helper. Generated by tcrt-automation-pomify.

Output path: tcrt_env.py (at repo root)

Use this variant instead of the ``tcrt_env`` conftest fixture when you prefer an
importable helper (e.g. Playwright async flows that don't take pytest fixtures).
The filename ``tcrt_env.py`` is NOT ``test_*`` / ``*_test`` so TCRT smart-scan
does not classify it as a test.

What it does
------------
At run time TCRT injects the per-environment config as a single masked CI
parameter ``TCRT_ENV_BUNDLE``; the Jenkins suite job writes the non-empty bundle
to ``repo/tcrt-env.json`` (workspace, gitignored), namespaced per script by the
script's repo-relative path (``ref_path``):

    { "tests/e2e/flow_login.py": {"BASE_URL": "…", "API_TOKEN": "…"}, ... }

``load_tcrt_env(__file__)`` reads that file, picks the namespace matching the
calling file's repo-relative path, and returns the variables by their fixed
names. When no environment is selected, ``tcrt-env.json`` is absent and it falls
back to ``os.environ`` per key — files with no ``TCRT_VARS`` are unaffected.

Usage from a test / flow:

    from tcrt_env import load_tcrt_env

    cfg = load_tcrt_env(__file__)            # __file__ → this script's namespace
    base_url = cfg["BASE_URL"]               # fixed name; value comes from TCRT
"""
from __future__ import annotations

import json
import os
from pathlib import Path


def _repo_root(start: Path) -> Path:
    for parent in [start, *start.parents]:
        if (parent / "tcrt-env.json").exists():
            return parent
    # Fall back: assume tests live one level under the repo root.
    return start.parents[1] if len(start.parents) > 1 else start.parent


def load_tcrt_env(caller_file: str) -> dict[str, str]:
    """Return the per-environment config for ``caller_file``, keyed by fixed names.

    Pass ``__file__`` from the calling test/flow so the namespace is resolved by
    that file's repo-relative path (``ref_path``). Returns an ``os.environ``-backed
    mapping when ``tcrt-env.json`` is absent (no environment selected).
    """
    caller = Path(caller_file).resolve()
    root = _repo_root(caller.parent)
    bundle_path = root / "tcrt-env.json"

    values: dict[str, str] = {}
    if bundle_path.exists():
        try:
            data = json.loads(bundle_path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            data = {}
        if isinstance(data, dict):
            rel_path = caller.relative_to(root).as_posix()
            ns = data.get(rel_path, {})
            if isinstance(ns, dict):
                values = dict(ns)

    class _Env(dict):
        def __missing__(self, key: str) -> str:
            return os.environ[key]

    return _Env(values)
