"""TCRT_VARS declaration snippet — generated by tcrt-automation-pomify.

Output path: top of EVERY rewritten test module (after the imports). It ships in
             every test template; this file is the canonical form to add when a
             module somehow lacks it.

Paste this **module-level** constant near the top of the test file (after the
imports). It declares — by NAME ONLY — the environment variables this script
needs. The VALUES never live here: register them in TCRT (Automation Hub →
Settings → Environments for shared params, Scripts tab → Script view → "Configure
variables" for per-script overrides). At run time TCRT injects them as
``TCRT_ENV_BUNDLE`` → ``repo/tcrt-env.json``; the settings loader reads them by
these fixed names. See ``references/environment-config.md``.

The block is MANDATORY in every rewritten test module — keep it even when the
script reads nothing (leave the list empty: ``TCRT_VARS = []``). List the names
detected from the source; do NOT invent names — an empty list is correct when
nothing is read. Each element is either a string (name; implies secret=False,
required=True) or a dict {"name", "secret", "required", "description"}. Names
must match ``^[A-Za-z_][A-Za-z0-9_]*$``. Mark obvious secrets ``secret: True``.
"""

# List the variable names this script actually reads (NO values here); leave the
# list empty when it reads none — but keep the block. Example entries:
TCRT_VARS = [
    # "BASE_URL",                                          # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
    # {"name": "TIMEOUT_MS", "secret": False, "required": False, "description": "request timeout"},
]
