"""conftest.py — Selenium driver + base_url fixtures + tcrt marker registration.

Generated by tcrt-automation-init. Output path: conftest.py (repo root).

TCRT smart-scan auto-excludes conftest.py from discovery.
"""
from __future__ import annotations

import os

import pytest
from selenium import webdriver


def pytest_configure(config: "pytest.Config") -> None:
    config.addinivalue_line(
        "markers",
        "tcrt(*tc_ids, link_type='covers'): declare TCRT manual test case coverage.",
    )


@pytest.fixture
def base_url() -> str:
    return os.environ.get("BASE_URL", "http://localhost:8000")


@pytest.fixture
def driver():
    options = webdriver.ChromeOptions()
    if os.environ.get("HEADLESS", "1") == "1":
        options.add_argument("--headless=new")
    drv = webdriver.Chrome(options=options)
    yield drv
    drv.quit()
