"""{{PAGE_CLASS}} — page object STUB (Selenium) generated by tcrt-automation-init.

Output path: pages/{{PAGE_MODULE}}.py

Inferred from the test case STEPS. Fill in ``path``, the class-level locator
tuples, and one action method per step verb. Contract: selectors are
class-level ``(By, value)`` tuples; action methods use ``self.find(...)`` so the
tuple is the single source of truth; NO assertions here; NO time.sleep.
"""
from __future__ import annotations

from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webdriver import WebDriver

from .base_page import BasePage


class {{PAGE_CLASS}}(BasePage):
    path = "/"  # TODO(init): set the real route, e.g. "/login" — TCG Admin: the resolved menuId route, e.g. "/73050"

    # TODO(init): one (By, value) tuple per element the steps touch, e.g.
    # EMAIL = (By.ID, "email")
    # PASSWORD = (By.ID, "password")
    # SUBMIT = (By.CSS_SELECTOR, "button[type=submit]")

    def __init__(self, driver: WebDriver, base_url: str) -> None:
        super().__init__(driver, base_url)

    # TODO(init): one action method per step verb. Example shape:
    #
    # def login(self, email: str, password: str) -> None:
    #     self.find(self.EMAIL).send_keys(email)
    #     self.find(self.PASSWORD).send_keys(password)
    #     self.click(self.SUBMIT)
