"""BasePage — shared helpers for Selenium page objects.

Generated by tcrt-automation-init. Output path: pages/base_page.py

Always wait via ``WebDriverWait`` — never ``time.sleep``.
"""
from __future__ import annotations

from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


class BasePage:
    path: str = "/"

    def __init__(self, driver: WebDriver, base_url: str, timeout: float = 10.0) -> None:
        self.driver = driver
        self.base_url = base_url
        self.wait = WebDriverWait(driver, timeout)

    def open(self) -> None:
        self.driver.get(f"{self.base_url}{self.path}")

    def find(self, locator: tuple[str, str]):
        return self.wait.until(EC.presence_of_element_located(locator))

    def click(self, locator: tuple[str, str]) -> None:
        self.wait.until(EC.element_to_be_clickable(locator)).click()

    def wait_for_url_contains(self, fragment: str) -> None:
        self.wait.until(EC.url_contains(fragment))

    def wait_for_visible(self, locator: tuple[str, str]):
        return self.wait.until(EC.visibility_of_element_located(locator))
