"""{{TC_TITLE}} — Selenium + pytest  ->  script_format: PYTEST

Generated by tcrt-automation-init.
Source:             TCRT MCP — team "{{TEAM}}", test case {{TC_NUMBER_CANONICAL}}
Generated:          {{TIMESTAMP_UTC}}
TCRT script_format: PYTEST   (filename starts with ``test_``)
Framework:          selenium + pytest

FILL-IN-THE-BLANK skeleton. The ``driver`` / ``base_url`` fixtures come from
conftest.py (copy templates/python/selenium_pytest/conftest.py). Workflow:
flesh out pages/{{PAGE_MODULE}}.py, replace each TODO, delete the skip
decorator, then run ``tcrt-automation-pomify`` to validate the POM contract.
"""
from __future__ import annotations

import pytest
from selenium.webdriver.remote.webdriver import WebDriver

from pages.{{PAGE_MODULE}} import {{PAGE_CLASS}}
from fixtures.test_data import DATA, SECRETS


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT
# (Settings → Environments / Script view → "Configure variables"). See SKILL.md §6.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


@pytest.mark.skip(reason="skeleton — implement the TODOs below, then remove this decorator")
@pytest.mark.tcrt("{{TC_NUMBER}}", link_type="{{LINK_TYPE}}")
def test_{{TEST_NAME}}(driver: WebDriver, base_url: str) -> None:
    # ───────────────────────────────────────────────────────────────────────
    # PRECONDITION (arrange):
    #   {{PRECONDITION}}
    # ───────────────────────────────────────────────────────────────────────
    {{PAGE_VAR}} = {{PAGE_CLASS}}(driver, base_url)
    {{PAGE_VAR}}.open()  # TODO(init): confirm entry point

    # ───────────────────────────────────────────────────────────────────────
    # STEPS (act):  one block per numbered step, quoted verbatim.
    # ───────────────────────────────────────────────────────────────────────
{{STEPS_BLOCK}}

    # ───────────────────────────────────────────────────────────────────────
    # EXPECTED RESULT (assert):  one assertion per expected outcome.
    # ───────────────────────────────────────────────────────────────────────
{{EXPECTED_BLOCK}}
