# Jenkins shell snippet — Allure Docker Service + TCRT callback
#
# Drop this block into the `post.always` (or equivalent) section of an existing
# Jenkinsfile / Groovy pipeline script. Use it for **single-script** TCRT runs;
# suite runs are auto-generated by TCRT from
# app/services/automation/templates/jenkins-suite-config.xml.j2 and already
# include this logic (defaults baked from config.yaml's
# automation_provider.allure block at suite-job creation time).
#
# Required pytest invocation (in your Test stage):
#   pytest --alluredir="${WORKSPACE}/allure-results" <your test paths>
#
# Required env vars — for single-script jobs, set these on the Jenkins agent
# or as global env / credentials. (Suite jobs receive the same values as job
# parameters, baked in from TCRT's config.yaml.)
#   ALLURE_BASE_URL     allure-docker-service root, e.g. http://allure.internal:5050
#   ALLURE_PROJECT_ID   Allure project id (must already exist; create with
#                         curl -XPOST $ALLURE_BASE_URL/allure-docker-service/projects \
#                              -H 'Content-Type: application/json' \
#                              -d '{"id":"<your-project-id>"}')
#   ALLURE_TOKEN        optional, only when SECURITY_ENABLED=1 on Allure
#   TCRT_WEBHOOK_URL    full webhook URL (TCRT_BASE_URL + /api/v1/webhooks/ci/<token>/run-status)
#
# Promote these Groovy-only values into env vars before the sh block so the
# script body can stay single-quoted:
#   script {
#     env.TCRT_WEBHOOK_RUN_ID = params.tcrt_run_id ?: ''
#     env.TCRT_WEBHOOK_STATUS = currentBuild.currentResult ?: 'UNKNOWN'
#   }

set +e

ALLURE_REPORT_URL=""

# --- 1. Upload allure-results to Allure Docker Service ---------------------
if [ -n "${ALLURE_BASE_URL:-}" ] && [ -n "${ALLURE_PROJECT_ID:-}" ] && [ -d "${WORKSPACE}/allure-results" ]; then
  AUTH_HEADER=""
  if [ -n "${ALLURE_TOKEN:-}" ]; then
    AUTH_HEADER="Authorization: Bearer ${ALLURE_TOKEN}"
  fi

  # Ensure the project exists on the Allure server. Idempotent: a 4xx
  # "already exists" response is ignored; only send-results is treated as
  # authoritative for failure.
  curl -sS -o /dev/null -X POST -H "Content-Type: application/json" \
    -H "${AUTH_HEADER}" \
    -d "{\"id\":\"${ALLURE_PROJECT_ID}\"}" \
    "${ALLURE_BASE_URL}/allure-docker-service/projects" \
    || echo "Allure project ensure failed (non-fatal; project may already exist or server unreachable)"

  for f in "${WORKSPACE}/allure-results/"*; do
    [ -f "$f" ] || continue
    curl -fsS -H "${AUTH_HEADER}" \
      -F "files[]=@${f}" \
      "${ALLURE_BASE_URL}/allure-docker-service/send-results?project_id=${ALLURE_PROJECT_ID}" \
      >/dev/null \
      || echo "Allure send-results upload failed for ${f} (non-fatal)"
  done

  # --- 2. Trigger report generation and capture the assigned URL -----------
  EXEC_NAME="tcrt-${TCRT_WEBHOOK_RUN_ID:-${BUILD_NUMBER}}"
  RESP=$(curl -fsS -H "${AUTH_HEADER}" \
    "${ALLURE_BASE_URL}/allure-docker-service/generate-report?project_id=${ALLURE_PROJECT_ID}&execution_name=${EXEC_NAME}" \
    || echo "")
  if [ -n "$RESP" ]; then
    ALLURE_REPORT_URL=$(echo "$RESP" | python3 -c "import sys,json; d=json.load(sys.stdin); print((d.get('data') or {}).get('report_url') or '')" 2>/dev/null || echo "")
  fi
fi

set -e

# --- 3. Notify TCRT with status (+ report_url when available) --------------
if [ -n "${TCRT_WEBHOOK_URL:-}" ]; then
  if [ -n "${ALLURE_REPORT_URL}" ]; then
    PAYLOAD=$(printf '{"tcrt_run_id":"%s","status":"%s","report_url":"%s"}' \
      "$TCRT_WEBHOOK_RUN_ID" "$TCRT_WEBHOOK_STATUS" "$ALLURE_REPORT_URL")
  else
    PAYLOAD=$(printf '{"tcrt_run_id":"%s","status":"%s"}' \
      "$TCRT_WEBHOOK_RUN_ID" "$TCRT_WEBHOOK_STATUS")
  fi
  curl -fsS -X POST "$TCRT_WEBHOOK_URL" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD" \
    || echo "TCRT webhook delivery failed (non-fatal)"
fi
