"""Shared Selenium fixtures.

Generated by tcrt-automation-pomify. Output path: conftest.py (at repo root or
tests/) — TCRT smart-scan auto-excludes any file named ``conftest.py``.

Adjust the driver setup to match the user's environment (local Chrome,
Selenium Grid URL, BrowserStack, etc.).
"""
from __future__ import annotations

import os

import pytest
from selenium import webdriver


@pytest.fixture(scope="session")
def base_url() -> str:
    return os.environ.get("BASE_URL", "http://localhost:3000")


@pytest.fixture()
def driver():
    options = webdriver.ChromeOptions()
    if os.environ.get("HEADLESS", "1") == "1":
        options.add_argument("--headless=new")
    drv = webdriver.Chrome(options=options)
    yield drv
    drv.quit()
