"""Login Page Object — Selenium + pytest.

Generated by tcrt-automation-pomify. Output path: pages/login_page.py
"""
from __future__ import annotations

from selenium.webdriver.common.by import By

from .base_page import BasePage


class LoginPage(BasePage):
    path = "/login"

    EMAIL = (By.ID, "email")
    PASSWORD = (By.ID, "password")
    SUBMIT = (By.CSS_SELECTOR, "button[type=submit]")
    ERROR_TOAST = (By.CSS_SELECTOR, "[role=alert]")

    def login(self, email: str, password: str) -> None:
        self.find(self.EMAIL).send_keys(email)
        self.find(self.PASSWORD).send_keys(password)
        self.click(self.SUBMIT)

    def error_text(self) -> str:
        return self.find(self.ERROR_TOAST).text
