"""Base page for Selenium + pytest page objects.

Generated by tcrt-automation-pomify. Output path: pages/base_page.py
"""
from __future__ import annotations

from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class BasePage:
    path: str = "/"

    def __init__(self, driver: WebDriver, base_url: str, timeout: float = 10.0) -> None:
        self.driver = driver
        self.base_url = base_url
        self.wait = WebDriverWait(driver, timeout)

    def open(self) -> None:
        self.driver.get(f"{self.base_url}{self.path}")

    def find(self, locator: tuple[str, str]) -> WebElement:
        return self.wait.until(EC.presence_of_element_located(locator))

    def click(self, locator: tuple[str, str]) -> None:
        self.wait.until(EC.element_to_be_clickable(locator)).click()

    def wait_for_url_contains(self, fragment: str) -> None:
        """Block until the current URL contains ``fragment``."""
        self.wait.until(EC.url_contains(fragment))

    def wait_for_visible(self, locator: tuple[str, str]) -> WebElement:
        """Block until ``locator`` is visible; return the element."""
        return self.wait.until(EC.visibility_of_element_located(locator))
