"""Login UI test — Pytest + Selenium (PYTEST).

Generated by tcrt-automation-pomify.
Source:           {{SOURCE_PATH}}
Generated:        {{TIMESTAMP_UTC}}
TCRT script_format: PYTEST
Framework:        pytest + selenium
Output path:      tests/ui/{{TEST_NAME}}.py
"""
from __future__ import annotations

import pytest

from pages.login_page import LoginPage


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT.
# See references/environment-config.md.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


@pytest.mark.ui
@pytest.mark.tcrt("{{TC_ID_HAPPY_PATH}}", link_type="primary")
def test_user_can_log_in_with_valid_credentials(driver, base_url):
    """Verifies the happy-path login flow with valid credentials."""
    login = LoginPage(driver, base_url)
    login.open()
    login.login("demo@example.com", "demo-password")
    login.wait_for_url_contains("/dashboard")
    assert driver.current_url.endswith("/dashboard")


@pytest.mark.ui
@pytest.mark.tcrt("{{TC_ID_BAD_PASSWORD}}")
def test_user_sees_error_on_wrong_password(driver, base_url):
    """Verifies that an error message is shown when the password is wrong."""
    login = LoginPage(driver, base_url)
    login.open()
    login.login("demo@example.com", "wrong")
    login.wait_for_visible(login.ERROR_TOAST)
    assert "Invalid" in login.error_text()
