"""Login Page Object — Playwright Python sync (pytest-playwright).

Generated by tcrt-automation-pomify. Output path: pages/login_page.py
"""
from __future__ import annotations

from playwright.sync_api import Page

from .base_page import BasePage


class LoginPage(BasePage):
    path = "/login"

    def __init__(self, page: Page) -> None:
        super().__init__(page)
        self.email_input = page.get_by_label("Email")
        self.password_input = page.get_by_label("Password")
        self.submit_button = page.get_by_role("button", name="Sign in")
        self.error_toast = page.get_by_role("alert")

    def login(self, email: str, password: str) -> None:
        self.email_input.fill(email)
        self.password_input.fill(password)
        self.submit_button.click()

    def error_text(self) -> str:
        return self.error_toast.inner_text()
