"""Base page for Playwright Python sync (pytest-playwright) page objects.

Generated by tcrt-automation-pomify. Output path: pages/base_page.py
"""
from __future__ import annotations

from playwright.sync_api import Page


class BasePage:
    path: str = "/"

    def __init__(self, page: Page) -> None:
        self.page = page

    def goto(self) -> None:
        self.page.goto(self.path)

    def wait_for_path(self, path: str, timeout_ms: int = 10_000) -> None:
        self.page.wait_for_url(f"**{path}", timeout=timeout_ms)
