"""Login UI test — Pytest + Playwright sync (PYTEST).

Generated by tcrt-automation-pomify.
Source:           {{SOURCE_PATH}}
Generated:        {{TIMESTAMP_UTC}}
TCRT script_format: PYTEST
Framework:        pytest + playwright (sync)
Output path:      tests/ui/{{TEST_NAME}}.py

Filename starts with ``test_`` so TCRT classifies as PYTEST and pytest
collects it. The Page Object lives in ``pages/`` so smart-scan excludes
it from test discovery.
"""
from __future__ import annotations

import pytest
from playwright.sync_api import Page, expect

from pages.login_page import LoginPage


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT.
# See references/environment-config.md.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


@pytest.mark.ui
@pytest.mark.tcrt("{{TC_ID_HAPPY_PATH}}", link_type="primary")
def test_user_can_log_in_with_valid_credentials(page: Page) -> None:
    """Verifies the happy-path login flow with valid credentials."""
    login = LoginPage(page)
    login.goto()
    login.login("demo@example.com", "demo-password")
    expect(page).to_have_url("**/dashboard")


@pytest.mark.ui
@pytest.mark.tcrt("{{TC_ID_BAD_PASSWORD}}")
def test_user_sees_error_on_wrong_password(page: Page) -> None:
    """Verifies that an error message is shown when the password is wrong."""
    login = LoginPage(page)
    login.goto()
    login.login("demo@example.com", "wrong")
    expect(login.error_toast).to_be_visible()
