"""initial_schema

Revision ID: 5c56712a0014
Revises: 
Create Date: 2026-03-11 16:39:07.461782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c56712a0014'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_story_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_story_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_story_maps_team_id'), ['team_id'], unique=False)

    op.create_table('user_story_map_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('children_ids', sa.JSON(), nullable=True),
    sa.Column('related_ids', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('jira_tickets', sa.JSON(), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('team_tags', sa.JSON(), nullable=True),
    sa.Column('aggregated_tickets', sa.JSON(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('as_a', sa.Text(), nullable=True),
    sa.Column('i_want', sa.Text(), nullable=True),
    sa.Column('so_that', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['user_story_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_story_map_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_story_map_nodes_map_id'), ['map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_story_map_nodes_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_story_map_nodes_node_type'), ['node_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_story_map_nodes_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_story_map_nodes_product'), ['product'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_story_map_nodes_team'), ['team'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_story_map_nodes_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_story_map_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_story_map_nodes_title'))
        batch_op.drop_index(batch_op.f('ix_user_story_map_nodes_team'))
        batch_op.drop_index(batch_op.f('ix_user_story_map_nodes_product'))
        batch_op.drop_index(batch_op.f('ix_user_story_map_nodes_parent_id'))
        batch_op.drop_index(batch_op.f('ix_user_story_map_nodes_node_type'))
        batch_op.drop_index(batch_op.f('ix_user_story_map_nodes_node_id'))
        batch_op.drop_index(batch_op.f('ix_user_story_map_nodes_map_id'))

    op.drop_table('user_story_map_nodes')
    with op.batch_alter_table('user_story_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_story_maps_team_id'))

    op.drop_table('user_story_maps')
    # ### end Alembic commands ###
