"""initial_schema

Revision ID: 7a26d2522198
Revises: 
Create Date: 2026-03-11 15:37:38.570311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a26d2522198'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lark_departments',
    sa.Column('department_id', sa.String(length=100), nullable=False),
    sa.Column('parent_department_id', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('leaders_json', sa.Text(), nullable=True),
    sa.Column('group_chat_employee_types_json', sa.Text(), nullable=True),
    sa.Column('direct_user_count', sa.Integer(), nullable=True),
    sa.Column('total_user_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    with op.batch_alter_table('lark_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lark_departments_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_lark_departments_parent_department_id'), ['parent_department_id'], unique=False)
        batch_op.create_index('ix_lark_dept_status', ['status'], unique=False)

    op.create_table('tcg_records',
    sa.Column('tcg_number', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tcg_number')
    )
    with op.batch_alter_table('tcg_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tcg_records_record_id'), ['record_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wiki_token', sa.String(length=255), nullable=False),
    sa.Column('test_case_table_id', sa.String(length=255), nullable=False),
    sa.Column('jira_project_key', sa.String(length=10), nullable=True),
    sa.Column('default_assignee', sa.String(length=255), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=True),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('auto_create_bugs', sa.Boolean(), nullable=False),
    sa.Column('default_priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='teamstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('test_case_count', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('lark_user_id', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('VIEWER', 'USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_email_active', ['email', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_lark_user_id'), ['lark_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index('ix_users_role_active', ['role', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_active_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sessions_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_sessions_jti_active', ['jti', 'is_revoked'], unique=False)
        batch_op.create_index('ix_sessions_user_active', ['user_id', 'is_revoked'], unique=False)

    op.create_table('adhoc_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jira_ticket', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DRAFT', 'ARCHIVED', name='testrunstatus'), nullable=False),
    sa.Column('test_version', sa.String(length=50), nullable=True),
    sa.Column('test_environment', sa.String(length=100), nullable=True),
    sa.Column('build_number', sa.String(length=100), nullable=True),
    sa.Column('related_tp_tickets_json', sa.Text(), nullable=True, comment='相關 JIRA Tickets 票號 JSON 陣列'),
    sa.Column('tp_tickets_search', sa.String(length=512), nullable=True, comment='JIRA Ticket 搜尋索引欄位'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='是否啟用通知'),
    sa.Column('notify_chat_ids_json', sa.Text(), nullable=True, comment='選擇的 Lark chat IDs（JSON 陣列）'),
    sa.Column('notify_chat_names_snapshot', sa.Text(), nullable=True, comment='群組名稱快照（JSON 陣列）'),
    sa.Column('notify_chats_search', sa.String(length=512), nullable=True, comment='群組名稱搜尋索引'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adhoc_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adhoc_runs_notify_chats_search'), ['notify_chats_search'], unique=False)
        batch_op.create_index(batch_op.f('ix_adhoc_runs_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adhoc_runs_tp_tickets_search'), ['tp_tickets_search'], unique=False)

    op.create_table('lark_users',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('open_id', sa.String(length=100), nullable=True),
    sa.Column('union_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('en_name', sa.String(length=255), nullable=True),
    sa.Column('enterprise_email', sa.String(length=255), nullable=True),
    sa.Column('primary_department_id', sa.String(length=100), nullable=True),
    sa.Column('department_ids_json', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('employee_type', sa.Integer(), nullable=True),
    sa.Column('employee_no', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('work_station', sa.String(length=255), nullable=True),
    sa.Column('mobile_visible', sa.Boolean(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('is_exited', sa.Boolean(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('is_resigned', sa.Boolean(), nullable=True),
    sa.Column('is_unjoin', sa.Boolean(), nullable=True),
    sa.Column('is_tenant_manager', sa.Boolean(), nullable=True),
    sa.Column('avatar_240', sa.String(length=500), nullable=True),
    sa.Column('avatar_640', sa.String(length=500), nullable=True),
    sa.Column('avatar_origin', sa.String(length=500), nullable=True),
    sa.Column('join_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_department_id'], ['lark_departments.department_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('lark_users', schema=None) as batch_op:
        batch_op.create_index('ix_lark_user_status', ['is_activated', 'is_exited'], unique=False)
        batch_op.create_index(batch_op.f('ix_lark_users_employee_type'), ['employee_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lark_users_enterprise_email'), ['enterprise_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_lark_users_is_activated'), ['is_activated'], unique=False)
        batch_op.create_index(batch_op.f('ix_lark_users_is_exited'), ['is_exited'], unique=False)
        batch_op.create_index(batch_op.f('ix_lark_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lark_users_open_id'), ['open_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lark_users_primary_department_id'), ['primary_department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lark_users_union_id'), ['union_id'], unique=True)

    op.create_table('mcp_machine_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('permission', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='mcpmachinecredentialstatus'), nullable=False),
    sa.Column('allow_all_teams', sa.Boolean(), nullable=False),
    sa.Column('team_scope_json', sa.Text(), nullable=True, comment='允許存取的 team_id 清單（JSON 陣列）'),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_mcp_machine_credentials_name'),
    sa.UniqueConstraint('token_hash', name='uq_mcp_machine_credentials_token_hash')
    )
    with op.batch_alter_table('mcp_machine_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_machine_credentials_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index('ix_mcp_machine_credentials_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_mcp_machine_credentials_status', ['status'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_is_used'), ['is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reset_tokens_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_reset_tokens_user', ['user_id', 'is_used'], unique=False)

    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_user', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('departments_discovered', sa.Integer(), nullable=True),
    sa.Column('departments_created', sa.Integer(), nullable=True),
    sa.Column('departments_updated', sa.Integer(), nullable=True),
    sa.Column('users_discovered', sa.Integer(), nullable=True),
    sa.Column('users_created', sa.Integer(), nullable=True),
    sa.Column('users_updated', sa.Integer(), nullable=True),
    sa.Column('users_duplicated', sa.Integer(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details_json', sa.Text(), nullable=True),
    sa.Column('result_summary_json', sa.Text(), nullable=True),
    sa.Column('department_result_json', sa.Text(), nullable=True),
    sa.Column('user_result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_history_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_sync_type'), ['sync_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_sync_history_team_time', ['team_id', 'start_time'], unique=False)

    op.create_table('test_case_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_test_case_set_name')
    )
    with op.batch_alter_table('test_case_sets', schema=None) as batch_op:
        batch_op.create_index('ix_test_case_sets_team', ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_case_sets_team_id'), ['team_id'], unique=False)

    op.create_table('test_run_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_version', sa.String(length=50), nullable=True),
    sa.Column('test_environment', sa.String(length=100), nullable=True),
    sa.Column('build_number', sa.String(length=100), nullable=True),
    sa.Column('related_tp_tickets_json', sa.Text(), nullable=True, comment='相關 JIRA Tickets 票號 JSON 陣列'),
    sa.Column('tp_tickets_search', sa.String(length=512), nullable=True, comment='JIRA Ticket 搜尋索引欄位'),
    sa.Column('test_case_set_ids_json', sa.Text(), nullable=True, comment='Test Case Set 範圍（JSON 陣列）'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='是否啟用通知'),
    sa.Column('notify_chat_ids_json', sa.Text(), nullable=True, comment='選擇的 Lark chat IDs（JSON 陣列）'),
    sa.Column('notify_chat_names_snapshot', sa.Text(), nullable=True, comment='群組名稱快照（JSON 陣列）'),
    sa.Column('notify_chats_search', sa.String(length=512), nullable=True, comment='群組名稱搜尋索引'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DRAFT', 'ARCHIVED', name='testrunstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('total_test_cases', sa.Integer(), nullable=True),
    sa.Column('executed_cases', sa.Integer(), nullable=True),
    sa.Column('passed_cases', sa.Integer(), nullable=True),
    sa.Column('failed_cases', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_run_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_run_configs_notify_chats_search'), ['notify_chats_search'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_configs_tp_tickets_search'), ['tp_tickets_search'], unique=False)

    op.create_table('test_run_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='testrunsetstatus'), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('related_tp_tickets_json', sa.Text(), nullable=True, comment='相關 JIRA Tickets 票號 JSON 陣列'),
    sa.Column('tp_tickets_search', sa.String(length=512), nullable=True, comment='JIRA Ticket 搜尋索引欄位'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_run_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_run_sets_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_sets_tp_tickets_search'), ['tp_tickets_search'], unique=False)

    op.create_table('user_team_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Enum('READ', 'WRITE', 'ADMIN', name='permissiontype'), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team_permission')
    )
    with op.batch_alter_table('user_team_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_team_permissions_permission'), ['permission'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_team_permissions_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_team_permissions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_team_perms_permission', ['permission'], unique=False)
        batch_op.create_index('ix_user_team_perms_team', ['team_id'], unique=False)
        batch_op.create_index('ix_user_team_perms_user', ['user_id'], unique=False)

    op.create_table('adhoc_run_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adhoc_run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adhoc_run_id'], ['adhoc_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adhoc_run_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adhoc_run_sheets_adhoc_run_id'), ['adhoc_run_id'], unique=False)

    op.create_table('ai_tc_helper_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('target_test_case_set_id', sa.Integer(), nullable=False),
    sa.Column('ticket_key', sa.String(length=64), nullable=True),
    sa.Column('review_locale', sa.String(length=16), nullable=False),
    sa.Column('output_locale', sa.String(length=16), nullable=False),
    sa.Column('initial_middle', sa.String(length=3), nullable=False),
    sa.Column('current_phase', sa.String(length=32), nullable=False),
    sa.Column('phase_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_test_case_set_id'], ['test_case_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tc_helper_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_sessions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_sessions_current_phase'), ['current_phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_sessions_phase_status'), ['phase_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_sessions_target_test_case_set_id'), ['target_test_case_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_sessions_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_ai_tc_helper_sessions_team_status', ['team_id', 'status'], unique=False)
        batch_op.create_index('ix_ai_tc_helper_sessions_team_updated', ['team_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_sessions_ticket_key'), ['ticket_key'], unique=False)

    op.create_table('test_case_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_section_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_section_id'], ['test_case_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_set_id'], ['test_case_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_set_id', 'parent_section_id', 'name', name='uq_section_name_in_parent')
    )
    with op.batch_alter_table('test_case_sections', schema=None) as batch_op:
        batch_op.create_index('ix_sections_set_level', ['test_case_set_id', 'level'], unique=False)
        batch_op.create_index('ix_sections_set_parent', ['test_case_set_id', 'parent_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_case_sections_test_case_set_id'), ['test_case_set_id'], unique=False)

    op.create_table('test_run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('test_case_number', sa.String(length=100), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_en_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_email', sa.String(length=255), nullable=True),
    sa.Column('assignee_json', sa.Text(), nullable=True),
    sa.Column('test_result', sa.Enum('PASSED', 'FAILED', 'RETEST', 'NOT_AVAILABLE', 'PENDING', 'NOT_REQUIRED', 'SKIP', name='testresultstatus'), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_duration', sa.Integer(), nullable=True),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('execution_results_json', sa.Text(), nullable=True),
    sa.Column('user_story_map_json', sa.Text(), nullable=True),
    sa.Column('tcg_json', sa.Text(), nullable=True),
    sa.Column('parent_record_json', sa.Text(), nullable=True),
    sa.Column('raw_fields_json', sa.Text(), nullable=True),
    sa.Column('bug_tickets_json', sa.Text(), nullable=True),
    sa.Column('result_files_uploaded', sa.Boolean(), nullable=False, comment='測試結果檔案是否已上傳到對應 Test Case'),
    sa.Column('result_files_count', sa.Integer(), nullable=False, comment='上傳的結果檔案數量'),
    sa.Column('upload_history_json', sa.Text(), nullable=True, comment='檔案上傳歷史記錄（JSON 格式）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['test_run_configs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'test_case_number', name='uq_test_run_item_config_case')
    )
    with op.batch_alter_table('test_run_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_run_items_config_id'), ['config_id'], unique=False)
        batch_op.create_index('ix_test_run_items_files_uploaded', ['result_files_uploaded'], unique=False)
        batch_op.create_index('ix_test_run_items_result', ['test_result'], unique=False)
        batch_op.create_index('ix_test_run_items_team', ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_items_test_case_number'), ['test_case_number'], unique=False)

    op.create_table('test_run_set_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['test_run_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['test_run_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', name='uq_test_run_set_membership_config')
    )
    with op.batch_alter_table('test_run_set_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_test_run_set_memberships_team_config', ['team_id', 'config_id'], unique=False)
        batch_op.create_index('ix_test_run_set_memberships_team_set', ['team_id', 'set_id'], unique=False)

    op.create_table('adhoc_run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('test_case_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=True),
    sa.Column('precondition', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('jira_tickets', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('bug_list', sa.Text(), nullable=True),
    sa.Column('test_result', sa.Enum('PASSED', 'FAILED', 'RETEST', 'NOT_AVAILABLE', 'PENDING', 'NOT_REQUIRED', 'SKIP', name='testresultstatus'), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('execution_results_json', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['adhoc_run_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adhoc_run_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adhoc_run_items_row_index'), ['row_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_adhoc_run_items_sheet_id'), ['sheet_id'], unique=False)

    op.create_table('ai_tc_helper_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_tc_helper_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'phase', name='uq_ai_tc_helper_draft_session_phase')
    )
    with op.batch_alter_table('ai_tc_helper_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_drafts_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_drafts_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_ai_tc_helper_drafts_session_phase', ['session_id', 'phase'], unique=False)

    op.create_table('ai_tc_helper_stage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_key', sa.String(length=64), nullable=True),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('input_audio_tokens', sa.Integer(), nullable=False),
    sa.Column('input_audio_cache_tokens', sa.Integer(), nullable=False),
    sa.Column('pretestcase_count', sa.Integer(), nullable=False),
    sa.Column('testcase_count', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('usage_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_tc_helper_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tc_helper_stage_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_stage_metrics_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_stage_metrics_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_ai_tc_helper_stage_metrics_session_phase', ['session_id', 'phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_stage_metrics_started_at'), ['started_at'], unique=False)
        batch_op.create_index('ix_ai_tc_helper_stage_metrics_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_stage_metrics_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_ai_tc_helper_stage_metrics_team_phase_time', ['team_id', 'phase', 'started_at'], unique=False)
        batch_op.create_index('ix_ai_tc_helper_stage_metrics_team_time', ['team_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_stage_metrics_ticket_key'), ['ticket_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tc_helper_stage_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('test_case_set_id', sa.Integer(), nullable=False),
    sa.Column('test_case_section_id', sa.Integer(), nullable=True),
    sa.Column('lark_record_id', sa.String(length=255), nullable=True),
    sa.Column('test_case_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=True),
    sa.Column('precondition', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('test_result', sa.Enum('PASSED', 'FAILED', 'RETEST', 'NOT_AVAILABLE', 'PENDING', 'NOT_REQUIRED', 'SKIP', name='testresultstatus'), nullable=True),
    sa.Column('assignee_json', sa.Text(), nullable=True),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('test_results_files_json', sa.Text(), nullable=True),
    sa.Column('user_story_map_json', sa.Text(), nullable=True),
    sa.Column('tcg_json', sa.Text(), nullable=True),
    sa.Column('parent_record_json', sa.Text(), nullable=True),
    sa.Column('raw_fields_json', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('local_version', sa.Integer(), nullable=False),
    sa.Column('lark_version', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('lark_created_at', sa.DateTime(), nullable=True),
    sa.Column('lark_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['test_case_section_id'], ['test_case_sections.id'], ),
    sa.ForeignKeyConstraint(['test_case_set_id'], ['test_case_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'test_case_number', name='uq_test_cases_team_case_number')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_lark_record_id'), ['lark_record_id'], unique=True)
        batch_op.create_index('ix_test_cases_number', ['test_case_number'], unique=False)
        batch_op.create_index('ix_test_cases_set_section', ['test_case_set_id', 'test_case_section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_sync_status'), ['sync_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_test_cases_team_priority', ['team_id', 'priority'], unique=False)
        batch_op.create_index('ix_test_cases_team_result', ['team_id', 'test_result'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_test_case_set_id'), ['test_case_set_id'], unique=False)

    op.create_table('test_run_item_result_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('prev_result', sa.Enum('PASSED', 'FAILED', 'RETEST', 'NOT_AVAILABLE', 'PENDING', 'NOT_REQUIRED', 'SKIP', name='testresultstatus'), nullable=True),
    sa.Column('new_result', sa.Enum('PASSED', 'FAILED', 'RETEST', 'NOT_AVAILABLE', 'PENDING', 'NOT_REQUIRED', 'SKIP', name='testresultstatus'), nullable=True),
    sa.Column('prev_executed_at', sa.DateTime(), nullable=True),
    sa.Column('new_executed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by_id', sa.String(length=64), nullable=True),
    sa.Column('changed_by_name', sa.String(length=255), nullable=True),
    sa.Column('change_source', sa.String(length=32), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['test_run_configs.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['test_run_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_run_item_result_history', schema=None) as batch_op:
        batch_op.create_index('ix_result_history_item_time', ['item_id', 'changed_at'], unique=False)
        batch_op.create_index('ix_result_history_team_config', ['team_id', 'config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_item_result_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_item_result_history_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_item_result_history_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_item_result_history_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_run_item_result_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_run_item_result_history_team_id'))
        batch_op.drop_index(batch_op.f('ix_test_run_item_result_history_item_id'))
        batch_op.drop_index(batch_op.f('ix_test_run_item_result_history_config_id'))
        batch_op.drop_index(batch_op.f('ix_test_run_item_result_history_changed_at'))
        batch_op.drop_index('ix_result_history_team_config')
        batch_op.drop_index('ix_result_history_item_time')

    op.drop_table('test_run_item_result_history')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_test_case_set_id'))
        batch_op.drop_index('ix_test_cases_team_result')
        batch_op.drop_index('ix_test_cases_team_priority')
        batch_op.drop_index(batch_op.f('ix_test_cases_team_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_sync_status'))
        batch_op.drop_index('ix_test_cases_set_section')
        batch_op.drop_index('ix_test_cases_number')
        batch_op.drop_index(batch_op.f('ix_test_cases_lark_record_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_checksum'))

    op.drop_table('test_cases')
    with op.batch_alter_table('ai_tc_helper_stage_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_stage_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_stage_metrics_ticket_key'))
        batch_op.drop_index('ix_ai_tc_helper_stage_metrics_team_time')
        batch_op.drop_index('ix_ai_tc_helper_stage_metrics_team_phase_time')
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_stage_metrics_team_id'))
        batch_op.drop_index('ix_ai_tc_helper_stage_metrics_status')
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_stage_metrics_started_at'))
        batch_op.drop_index('ix_ai_tc_helper_stage_metrics_session_phase')
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_stage_metrics_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_stage_metrics_phase'))

    op.drop_table('ai_tc_helper_stage_metrics')
    with op.batch_alter_table('ai_tc_helper_drafts', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_tc_helper_drafts_session_phase')
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_drafts_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_drafts_phase'))

    op.drop_table('ai_tc_helper_drafts')
    with op.batch_alter_table('adhoc_run_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adhoc_run_items_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_adhoc_run_items_row_index'))

    op.drop_table('adhoc_run_items')
    with op.batch_alter_table('test_run_set_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_test_run_set_memberships_team_set')
        batch_op.drop_index('ix_test_run_set_memberships_team_config')

    op.drop_table('test_run_set_memberships')
    with op.batch_alter_table('test_run_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_run_items_test_case_number'))
        batch_op.drop_index('ix_test_run_items_team')
        batch_op.drop_index('ix_test_run_items_result')
        batch_op.drop_index('ix_test_run_items_files_uploaded')
        batch_op.drop_index(batch_op.f('ix_test_run_items_config_id'))

    op.drop_table('test_run_items')
    with op.batch_alter_table('test_case_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_case_sections_test_case_set_id'))
        batch_op.drop_index('ix_sections_set_parent')
        batch_op.drop_index('ix_sections_set_level')

    op.drop_table('test_case_sections')
    with op.batch_alter_table('ai_tc_helper_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_sessions_ticket_key'))
        batch_op.drop_index('ix_ai_tc_helper_sessions_team_updated')
        batch_op.drop_index('ix_ai_tc_helper_sessions_team_status')
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_sessions_team_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_sessions_target_test_case_set_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_sessions_phase_status'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_sessions_current_phase'))
        batch_op.drop_index(batch_op.f('ix_ai_tc_helper_sessions_created_by_user_id'))

    op.drop_table('ai_tc_helper_sessions')
    with op.batch_alter_table('adhoc_run_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adhoc_run_sheets_adhoc_run_id'))

    op.drop_table('adhoc_run_sheets')
    with op.batch_alter_table('user_team_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_team_perms_user')
        batch_op.drop_index('ix_user_team_perms_team')
        batch_op.drop_index('ix_user_team_perms_permission')
        batch_op.drop_index(batch_op.f('ix_user_team_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_team_permissions_team_id'))
        batch_op.drop_index(batch_op.f('ix_user_team_permissions_permission'))

    op.drop_table('user_team_permissions')
    with op.batch_alter_table('test_run_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_run_sets_tp_tickets_search'))
        batch_op.drop_index(batch_op.f('ix_test_run_sets_team_id'))

    op.drop_table('test_run_sets')
    with op.batch_alter_table('test_run_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_run_configs_tp_tickets_search'))
        batch_op.drop_index(batch_op.f('ix_test_run_configs_notify_chats_search'))

    op.drop_table('test_run_configs')
    with op.batch_alter_table('test_case_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_case_sets_team_id'))
        batch_op.drop_index('ix_test_case_sets_team')

    op.drop_table('test_case_sets')
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_history_team_time')
        batch_op.drop_index(batch_op.f('ix_sync_history_team_id'))
        batch_op.drop_index(batch_op.f('ix_sync_history_sync_type'))
        batch_op.drop_index(batch_op.f('ix_sync_history_status'))
        batch_op.drop_index(batch_op.f('ix_sync_history_start_time'))

    op.drop_table('sync_history')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_tokens_user')
        batch_op.drop_index('ix_reset_tokens_expires')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_is_used'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('mcp_machine_credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_mcp_machine_credentials_status')
        batch_op.drop_index('ix_mcp_machine_credentials_expires_at')
        batch_op.drop_index(batch_op.f('ix_mcp_machine_credentials_created_by_user_id'))

    op.drop_table('mcp_machine_credentials')
    with op.batch_alter_table('lark_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lark_users_union_id'))
        batch_op.drop_index(batch_op.f('ix_lark_users_primary_department_id'))
        batch_op.drop_index(batch_op.f('ix_lark_users_open_id'))
        batch_op.drop_index(batch_op.f('ix_lark_users_name'))
        batch_op.drop_index(batch_op.f('ix_lark_users_is_exited'))
        batch_op.drop_index(batch_op.f('ix_lark_users_is_activated'))
        batch_op.drop_index(batch_op.f('ix_lark_users_enterprise_email'))
        batch_op.drop_index(batch_op.f('ix_lark_users_employee_type'))
        batch_op.drop_index('ix_lark_user_status')

    op.drop_table('lark_users')
    with op.batch_alter_table('adhoc_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adhoc_runs_tp_tickets_search'))
        batch_op.drop_index(batch_op.f('ix_adhoc_runs_team_id'))
        batch_op.drop_index(batch_op.f('ix_adhoc_runs_notify_chats_search'))

    op.drop_table('adhoc_runs')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_active')
        batch_op.drop_index('ix_sessions_jti_active')
        batch_op.drop_index('ix_sessions_expires')
        batch_op.drop_index(batch_op.f('ix_active_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_jti'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_expires_at'))

    op.drop_table('active_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index('ix_users_role_active')
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_lark_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index('ix_users_email_active')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('teams')
    with op.batch_alter_table('tcg_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tcg_records_record_id'))

    op.drop_table('tcg_records')
    with op.batch_alter_table('lark_departments', schema=None) as batch_op:
        batch_op.drop_index('ix_lark_dept_status')
        batch_op.drop_index(batch_op.f('ix_lark_departments_parent_department_id'))
        batch_op.drop_index(batch_op.f('ix_lark_departments_level'))

    op.drop_table('lark_departments')
    # ### end Alembic commands ###
