"""TCRT_VARS block — generated by tcrt-automation-init.

Output path: top of the generated test module (after the imports). It ships in
             every test template; this file is the canonical form to add when a
             module somehow lacks it (e.g. integrating into existing tests).

TCRT manages per-environment config values (Prod / SIT / dev) for scripts IN
TCRT, not in the repo. Declare — by NAME ONLY — the variables this script reads.
The VALUES never live here: register them in TCRT (Automation Hub → Settings →
Environments for shared params, Scripts tab → Script view → "Configure variables" for
per-script overrides). At run time TCRT injects them as TCRT_ENV_BUNDLE →
repo/tcrt-env.json; the settings loader (tcrt_env fixture / tcrt_env.py) reads
them by these fixed names. See references/tcrt-format-rules.md §7 and the pomify
skill's references/environment-config.md for the full grammar.

The block is MANDATORY in every generated test module — keep it even when the
script reads nothing (leave the list empty: ``TCRT_VARS = []``). Fill in only
the names this test actually uses. Each element is either a string (name;
implies secret=False, required=True) or a dict
{"name", "secret", "required", "description"}. Names must match
``^[A-Za-z_][A-Za-z0-9_]*$``. Mark obvious secrets ``secret: True``.
"""

# Declare the variable NAMES this script reads (NO values here), then read them
# via the tcrt_env fixture / load_tcrt_env(__file__) loader. Leave the list
# empty when the script needs no per-environment config — but keep the block.
TCRT_VARS = [
    # "BASE_URL",                                          # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]
