"""Example Page Object — login.

Generated by tcrt-automation-pomify. Output path: pages/login_page.py

Tweak ``path``, locators, and action method bodies to match the user's app.
The shape (constructor takes ``page``, locators are instance attrs, actions
are async methods, no assertions) is the contract — keep it.
"""
from __future__ import annotations

from playwright.async_api import Page

from .base_page import BasePage


class LoginPage(BasePage):
    path = "/login"

    def __init__(self, page: Page) -> None:
        super().__init__(page)
        self.email_input = page.get_by_label("Email")
        self.password_input = page.get_by_label("Password")
        self.submit_button = page.get_by_role("button", name="Sign in")
        self.error_toast = page.get_by_role("alert")

    async def login(self, email: str, password: str) -> None:
        await self.email_input.fill(email)
        await self.password_input.fill(password)
        await self.submit_button.click()

    async def error_text(self) -> str:
        return await self.error_toast.inner_text()
