"""Base page for Playwright Python async page objects.

Generated by tcrt-automation-pomify. Output path: pages/base_page.py
"""
from __future__ import annotations

from playwright.async_api import Page


class BasePage:
    """Common helpers shared by every Page Object.

    Subclasses override ``path`` and create locators in ``__init__`` (calling
    ``super().__init__(page)`` first). Do NOT put assertions here — tests own
    assertions.
    """

    path: str = "/"

    def __init__(self, page: Page) -> None:
        self.page = page

    async def goto(self) -> None:
        await self.page.goto(self.path)

    async def wait_for_path(self, path: str, timeout_ms: int = 10_000) -> None:
        await self.page.wait_for_url(f"**{path}", timeout=timeout_ms)
