"""Login flow — Playwright Python async (PLAYWRIGHT_PY_ASYNC).

Generated by tcrt-automation-pomify.
Source:           {{SOURCE_PATH}}
Generated:        {{TIMESTAMP_UTC}}
TCRT script_format: PLAYWRIGHT_PY_ASYNC
Framework:        playwright (async)
Output path:      tests/e2e/{{FLOW_NAME}}.py

Filename does NOT start with ``test_`` and does NOT end with ``_test.py``,
so TCRT classifies this file as PLAYWRIGHT_PY_ASYNC. Test FUNCTIONS still
use the ``test_`` prefix so smart-scan's AST walker can extract names.
"""
from __future__ import annotations

import pytest
from playwright.async_api import Page, expect

from pages.login_page import LoginPage


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT.
# See references/environment-config.md.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


@pytest.mark.tcrt("{{TC_ID_HAPPY_PATH}}", link_type="primary")
async def test_user_can_log_in_with_valid_credentials(page: Page) -> None:
    """Verifies the happy-path login flow with valid credentials."""
    login = LoginPage(page)
    await login.goto()
    await login.login("demo@example.com", "demo-password")
    await expect(page).to_have_url("**/dashboard")


@pytest.mark.tcrt("{{TC_ID_BAD_PASSWORD}}")
async def test_user_sees_error_on_wrong_password(page: Page) -> None:
    """Verifies that an error message is shown when the password is wrong."""
    login = LoginPage(page)
    await login.goto()
    await login.login("demo@example.com", "wrong")
    await expect(login.error_toast).to_be_visible()
