"""initial_schema

Revision ID: 7f71847167e1
Revises: 
Create Date: 2026-03-11 16:39:07.470256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f71847167e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', name='actiontype'), nullable=False),
    sa.Column('resource_type', sa.Enum('TEAM_SETTING', 'TEST_RUN', 'TEST_CASE', 'TEST_CASE_SET', 'TEST_CASE_SECTION', 'USER_STORY_MAP', 'USER', 'AUTH', 'PERMISSION', 'ATTACHMENT', 'SYSTEM', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('action_brief', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='auditseverity'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action_time', ['action_type', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_audit_role_time', ['role', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_severity_time', ['severity', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_time_team', ['timestamp', 'team_id'], unique=False)
        batch_op.create_index('idx_audit_user_time', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_username_time', ['username', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_team_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_severity'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_role'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action_type'))
        batch_op.drop_index('idx_audit_username_time')
        batch_op.drop_index('idx_audit_user_time')
        batch_op.drop_index('idx_audit_time_team')
        batch_op.drop_index('idx_audit_severity_time')
        batch_op.drop_index('idx_audit_role_time')
        batch_op.drop_index('idx_audit_resource')
        batch_op.drop_index('idx_audit_action_time')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
