"""{{TC_TITLE}} - pytest API (httpx)  ->  script_format: PYTEST

Generated by tcrt-automation-init.
Source:             TCRT MCP - team "{{TEAM}}", test case {{TC_NUMBER_CANONICAL}}
Generated:          {{TIMESTAMP_UTC}}
TCRT script_format: PYTEST   (filename starts with ``test_``)
Framework:          pytest + httpx (API-only; no browser driver)

FILL-IN-THE-BLANK skeleton. Every step / expected result below is quoted
verbatim from the test case. Workflow:
  1. Set API_BASE_URL and fill in the request method / path / body / headers.
  2. Replace each ``TODO`` line with a real HTTP request / assertion.
  3. Delete the ``@pytest.mark.skip`` decorator.
  4. Run ``tcrt-automation-pomify`` once filled in to validate TCRT format.
"""
from __future__ import annotations

import os

import pytest

from fixtures.test_data import DATA, SECRETS


# ── TCRT_VARS — per-environment variable NAMES this script reads ─────────────
# MANDATORY for every TCRT script: keep this block even when the script reads
# nothing (leave the list empty). NO values here — register them in TCRT
# (Settings → Environments / Script view → "Configure variables"). See SKILL.md §6.
TCRT_VARS = [
    # "BASE_URL",                                        # secret=False, required=True
    # {"name": "API_TOKEN", "secret": True, "required": True},
]


httpx = pytest.importorskip("httpx")
API_BASE_URL = os.environ.get("API_BASE_URL", "https://example.invalid")  # TODO(init): set the real API host


@pytest.mark.skip(reason="skeleton - implement the TODOs below, then remove this decorator")
@pytest.mark.tcrt("{{TC_NUMBER}}", link_type="{{LINK_TYPE}}")
def test_{{TEST_NAME}}() -> None:
    # -----------------------------------------------------------------------
    # PRECONDITION (arrange):
    #   {{PRECONDITION}}
    # -----------------------------------------------------------------------
    # TODO(init): prepare prerequisite records or auth tokens with HTTP calls
    # when the precondition requires API-side setup.

    with httpx.Client(base_url=API_BASE_URL, timeout=30.0) as client:
        # -------------------------------------------------------------------
        # STEPS (act): one block per numbered step, quoted verbatim.
        # -------------------------------------------------------------------
{{STEPS_BLOCK}}

        response: httpx.Response | None = None
        # TODO(init): response = client.request("GET", "/path", headers={}, json={})

        # -------------------------------------------------------------------
        # EXPECTED RESULT (assert): one assertion per expected outcome.
        # -------------------------------------------------------------------
{{EXPECTED_BLOCK}}

        _ = (client, response, DATA, SECRETS)

    raise NotImplementedError("TODO(init): implement API request/assertions before removing skip")
