"""工具目錄：Test Cases（tool-matrix.md 第 2 節，2.1–2.17）。"""

from __future__ import annotations

from app.auth.models import PermissionType
from app.services.assistant.schema_helpers import TEST_DATA_ITEM_SCHEMA, body, s_array, s_int, s_str
from app.services.assistant.tool_registry import (
    HIGH_IMPACT,
    IRREVERSIBLE,
    READ,
    REVERSIBLE_WRITE,
    AssistantTool,
)

_TC_LIST = ("record_id", "test_case_number", "title", "priority", "test_result", "assignee_name",
            "test_case_set_id", "test_case_section_id", "section_name", "section_path",
            "tcg_tickets", "updated_at")
_TC_DETAIL = _TC_LIST + ("precondition", "steps", "expected_result", "test_data", "attachments")
_PAGE = ("skip", "limit", "total", "has_next", "next_cursor")

_FILTER_QUERY = {
    "search": s_str("keyword search across title/number"),
    "priority_filter": s_str("filter by priority"),
    "test_result_filter": s_str("filter by last test result"),
    "assignee_filter": s_str("filter by assignee name"),
    "tcg_filter": s_str("filter by TCG/JIRA ticket"),
    "set_id": s_int("filter by test_case_set_id"),
    "sort_by": s_str("sort field"),
    "sort_order": s_str("asc|desc", enum=["asc", "desc"]),
    "skip": s_int("pagination offset"),
    "limit": s_int("page size"),
}

_CREATE_UPDATE_FIELDS = {
    "test_case_number": s_str("unique case number, required on create"),
    "title": s_str("case title"),
    "priority": s_str("P0|P1|P2|P3", enum=["P0", "P1", "P2", "P3"]),
    "precondition": s_str(),
    "steps": s_str(),
    "expected_result": s_str(),
    "tcg": s_array(s_str(), "related JIRA/TCG ticket keys"),
    "test_data": s_array(TEST_DATA_ITEM_SCHEMA, "structured test data rows"),
}

TOOLS = [
    AssistantTool(
        name="list_test_cases",
        method="GET",
        path_template="/api/teams/{team_id}/testcases/",
        summary="List test cases in the current team with filters.",
        permission=PermissionType.READ,
        risk_level=READ,
        query_params=_FILTER_QUERY,
        team_check="inject",
        resource_team_resolver=None,
        projection=_TC_LIST + _PAGE,
    ),
    AssistantTool(
        name="count_test_cases",
        method="GET",
        path_template="/api/teams/{team_id}/testcases/count",
        summary="Count test cases matching filters.",
        permission=PermissionType.READ,
        risk_level=READ,
        query_params=_FILTER_QUERY,
        team_check="inject",
        projection=("total",),
    ),
    AssistantTool(
        name="get_test_case",
        method="GET",
        path_template="/api/teams/{team_id}/testcases/{record_id}",
        summary="Get full detail of a single test case.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("record_id",),
        team_check="inject",
        projection=_TC_DETAIL,
    ),
    AssistantTool(
        name="find_test_cases_by_tickets",
        method="GET",
        path_template="/api/teams/{team_id}/testcases/by-tickets",
        summary="Find test cases linked to given JIRA/TCG ticket numbers (comma-separated).",
        permission=PermissionType.READ,
        risk_level=READ,
        query_params={"tickets": s_str("comma-separated ticket keys")},
        required_query=("tickets",),
        team_check="inject",
        projection=("record_id", "test_case_number", "title", "priority", "jira_tickets"),
    ),
    AssistantTool(
        name="create_test_case",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/",
        summary="Create a new test case.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        body_schema=body(
            {**_CREATE_UPDATE_FIELDS, "test_case_set_id": s_int(), "test_case_section_id": s_int()},
            required=["test_case_number", "title"],
        ),
        team_check="resolve",
        resource_team_resolver="create_test_case_scope",
        projection=_TC_DETAIL,
        confirmation_action_key="assistant.action.create_test_case",
        warning_key="assistant.warning.confirm_write",
        target_resolver="create",
        credential_check_fields=("test_data",),
    ),
    AssistantTool(
        name="update_test_case",
        method="PUT",
        path_template="/api/teams/{team_id}/testcases/{record_id}",
        summary="Update a test case's content fields (not its set/section).",
        permission=PermissionType.WRITE,
        risk_level="idempotent_write",
        path_params=("record_id",),
        body_schema=body(_CREATE_UPDATE_FIELDS),
        team_check="inject",
        # team_check="inject" 信任對話綁定 team（無需 resolve_team 查詢），但 target_resolver="single"
        # 的 confirmation summary 仍需要 resource_team_resolver 才能查得 stable identity/label——
        # 兩者用途獨立，此欄位不影響 team 驗證策略。
        resource_team_resolver="test_case",
        projection=_TC_DETAIL,
        confirmation_action_key="assistant.action.update_test_case",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
        credential_check_fields=("test_data",),
    ),
    AssistantTool(
        name="delete_test_case",
        method="DELETE",
        path_template="/api/teams/{team_id}/testcases/{record_id}",
        summary="Permanently delete a test case.",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        path_params=("record_id",),
        team_check="inject",
        resource_team_resolver="test_case",
        projection=(),
        has_no_response_body=True,
        confirmation_action_key="assistant.action.delete_test_case",
        warning_key="assistant.warning.irreversible",
        target_resolver="single",
    ),
    AssistantTool(
        name="move_test_case_scope",
        method="PUT",
        path_template="/api/teams/{team_id}/testcases/{record_id}",
        summary="Move a test case to a different set/section.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("record_id",),
        body_schema=body(
            {"test_case_set_id": s_int(), "test_case_section_id": s_int()},
        ),
        team_check="resolve",
        resource_team_resolver="move_test_case_scope",
        projection=_TC_DETAIL + ("cleanup_summary",),
        confirmation_action_key="assistant.action.move_test_case_scope",
        warning_key="assistant.warning.high_impact",
        target_resolver="single",
    ),
    AssistantTool(
        name="bulk_create_test_cases",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/bulk_create",
        summary="Bulk-create multiple test cases in one call.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        body_schema=body(
            {
                "items": s_array(body(_CREATE_UPDATE_FIELDS, required=["test_case_number", "title"])),
                "test_case_set_id": s_int(),
                "test_case_section_id": s_int(),
            },
            required=["items"],
        ),
        team_check="resolve",
        resource_team_resolver="create_test_case_scope",
        projection=("success", "created_count", "duplicates", "errors"),
        confirmation_action_key="assistant.action.bulk_create_test_cases",
        warning_key="assistant.warning.high_impact",
        target_resolver="batch",
        credential_check_fields=("items",),
    ),
    AssistantTool(
        name="bulk_clone_test_cases",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/bulk_clone",
        summary="Clone existing test cases under new case numbers.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        body_schema=body(
            {
                "items": s_array(
                    body(
                        # Align with app.api.test_cases.BulkCloneItem field names.
                        {"source_record_id": s_str(), "test_case_number": s_str(), "title": s_str()},
                        required=["source_record_id", "test_case_number"],
                    )
                )
            },
            required=["items"],
        ),
        team_check="resolve",
        resource_team_resolver="bulk_clone_test_cases",
        projection=("success", "created_count", "duplicates", "errors"),
        confirmation_action_key="assistant.action.bulk_clone_test_cases",
        warning_key="assistant.warning.high_impact",
        target_resolver="batch",
    ),
    AssistantTool(
        name="preview_move_test_set_impact",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/impact-preview/move-test-set",
        summary="Preview the impact of moving test cases to another test-case-set before doing it.",
        permission=PermissionType.WRITE,
        risk_level=READ,
        body_schema=body(
            {"record_ids": s_array(s_int()), "target_test_set_id": s_int()},
            required=["record_ids", "target_test_set_id"],
        ),
        team_check="resolve",
        resource_team_resolver="preview_move_test_set_impact",
        projection=("impacted_item_count", "trigger", "target_test_case_set_id", "source_test_case_set_id", "impacted_test_runs"),
    ),
    AssistantTool(
        name="list_test_case_attachments",
        method="GET",
        path_template="/api/teams/{team_id}/testcases/{test_case_id:int}/attachments",
        summary="List attachments on a test case.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("test_case_id",),
        team_check="resolve",
        resource_team_resolver="test_case",
        projection=("files", "count"),
    ),
    AssistantTool(
        name="upload_test_case_attachment",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/{test_case_id:int}/attachments",
        summary="Upload a chat-provided file as a test case attachment.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        path_params=("test_case_id",),
        multipart_file_param="files",
        team_check="resolve",
        resource_team_resolver="test_case",
        projection=("uploaded", "files"),
        confirmation_action_key="assistant.action.upload_test_case_attachment",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="delete_test_case_attachment",
        method="DELETE",
        path_template="/api/teams/{team_id}/testcases/{test_case_id:int}/attachments/{target}",
        summary="Delete a test case attachment.",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        path_params=("test_case_id", "target"),
        team_check="resolve",
        resource_team_resolver="test_case",
        projection=("deleted", "remaining"),
        confirmation_action_key="assistant.action.delete_test_case_attachment",
        warning_key="assistant.warning.irreversible",
        target_resolver="single",
    ),
    AssistantTool(
        name="batch_update_test_cases",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/batch",
        summary="Batch-update priority or TCG tickets on multiple test cases.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        body_schema=body(
            {
                "operation": s_str("update_priority|update_tcg", enum=["update_priority", "update_tcg"]),
                "record_ids": s_array(s_int()),
                "update_data": body({"priority": s_str(), "tcg": s_array(s_str())}),
            },
            required=["operation", "record_ids"],
        ),
        team_check="inject",
        resource_team_resolver="batch_test_cases_same_team",
        projection=("processed_count", "success_count", "success", "error_count", "error_messages"),
        confirmation_action_key="assistant.action.batch_update_test_cases",
        warning_key="assistant.warning.high_impact",
        target_resolver="batch",
    ),
    AssistantTool(
        name="batch_move_test_cases",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/batch",
        summary="Batch-move multiple test cases to a different section or test-case-set.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        body_schema=body(
            {
                "operation": s_str("update_section|update_test_set", enum=["update_section", "update_test_set"]),
                "record_ids": s_array(s_int()),
                "update_data": body({"test_case_section_id": s_int(), "test_case_set_id": s_int()}),
            },
            required=["operation", "record_ids", "update_data"],
        ),
        team_check="resolve",
        resource_team_resolver="batch_move_test_cases",
        projection=("processed_count", "success_count", "success", "error_count", "error_messages", "cleanup_summary"),
        confirmation_action_key="assistant.action.batch_move_test_cases",
        warning_key="assistant.warning.high_impact",
        target_resolver="batch",
    ),
    AssistantTool(
        name="batch_delete_test_cases",
        method="POST",
        path_template="/api/teams/{team_id}/testcases/batch",
        summary="Batch-delete multiple test cases permanently.",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        body_schema=body({"record_ids": s_array(s_int())}, required=["record_ids"]),
        fixed_body={"operation": "delete"},
        team_check="inject",
        resource_team_resolver="batch_test_cases_same_team",
        projection=("processed_count", "success_count", "success", "error_count", "error_messages"),
        confirmation_action_key="assistant.action.batch_delete_test_cases",
        warning_key="assistant.warning.irreversible",
        target_resolver="batch",
    ),
]
