"""工具目錄：Test Case Sets / Sections（tool-matrix.md 第 3 節，3.1–3.10）。"""

from __future__ import annotations

from app.auth.models import PermissionType
from app.services.assistant.schema_helpers import body, s_int, s_str
from app.services.assistant.tool_registry import (
    IDEMPOTENT_WRITE,
    IRREVERSIBLE,
    READ,
    REVERSIBLE_WRITE,
    AssistantTool,
)

_SET_FIELDS = {"name": s_str(), "description": s_str()}
_SET_PROJECTION = ("id", "name", "description", "is_default", "test_case_count", "created_at", "updated_at")
_SECTION_FIELDS = {"name": s_str(), "description": s_str(), "parent_id": s_int()}
_SECTION_PROJECTION = ("id", "test_case_set_id", "name", "description", "parent_section_id", "level", "sort_order", "created_at", "updated_at")

TOOLS = [
    AssistantTool(
        name="list_test_case_sets",
        method="GET",
        path_template="/api/teams/{team_id}/test-case-sets",
        summary="List test case sets in the current team.",
        permission=PermissionType.READ,
        risk_level=READ,
        team_check="inject",
        projection=_SET_PROJECTION,
    ),
    AssistantTool(
        name="get_test_case_set",
        method="GET",
        path_template="/api/teams/{team_id}/test-case-sets/{set_id}",
        summary="Get a test case set with its section tree and counts.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("set_id",),
        team_check="inject",
        resource_team_resolver="test_case_set",
        projection=_SET_PROJECTION + ("sections",),
    ),
    AssistantTool(
        name="create_test_case_set",
        method="POST",
        path_template="/api/teams/{team_id}/test-case-sets",
        summary="Create a new test case set.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        body_schema=body(_SET_FIELDS, required=["name"]),
        team_check="inject",
        projection=_SET_PROJECTION,
        confirmation_action_key="assistant.action.create_test_case_set",
        warning_key="assistant.warning.confirm_write",
        target_resolver="create",
    ),
    AssistantTool(
        name="update_test_case_set",
        method="PUT",
        path_template="/api/teams/{team_id}/test-case-sets/{set_id}",
        summary="Update a test case set's name/description.",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,
        path_params=("set_id",),
        body_schema=body(_SET_FIELDS),
        team_check="inject",
        resource_team_resolver="test_case_set",
        projection=_SET_PROJECTION,
        confirmation_action_key="assistant.action.update_test_case_set",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="preview_delete_test_case_set_impact",
        method="GET",
        path_template="/api/teams/{team_id}/test-case-sets/{set_id}/impact-preview",
        summary="Preview the impact of deleting a test case set.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("set_id",),
        team_check="inject",
        resource_team_resolver="test_case_set",
        projection=("impacted_item_count", "trigger", "target_test_case_set_id", "source_test_case_set_id", "impacted_test_runs"),
    ),
    AssistantTool(
        name="delete_test_case_set",
        method="DELETE",
        path_template="/api/teams/{team_id}/test-case-sets/{set_id}",
        summary="Permanently delete a test case set (test cases move to the team's default set).",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        path_params=("set_id",),
        team_check="inject",
        resource_team_resolver="test_case_set",
        projection=("cleanup_summary", "moved_test_case_count"),
        confirmation_action_key="assistant.action.delete_test_case_set",
        warning_key="assistant.warning.irreversible",
        target_resolver="single",
    ),
    AssistantTool(
        name="list_test_case_sections",
        method="GET",
        path_template="/api/test-case-sets/{set_id}/sections",
        summary="List sections (folder tree) within a test case set.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("set_id",),
        team_check="resolve",
        resource_team_resolver="test_case_set",
        projection=_SECTION_PROJECTION,
    ),
    AssistantTool(
        name="create_test_case_section",
        method="POST",
        path_template="/api/test-case-sets/{set_id}/sections",
        summary="Create a new section inside a test case set.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        path_params=("set_id",),
        body_schema=body(_SECTION_FIELDS, required=["name"]),
        team_check="resolve",
        resource_team_resolver="test_case_set",
        projection=_SECTION_PROJECTION,
        confirmation_action_key="assistant.action.create_test_case_section",
        warning_key="assistant.warning.confirm_write",
        target_resolver="create",
    ),
    AssistantTool(
        name="update_test_case_section",
        method="PUT",
        path_template="/api/test-case-sets/{set_id}/sections/{section_id}",
        summary="Update a section's name/description/parent.",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,
        path_params=("set_id", "section_id"),
        body_schema=body(_SECTION_FIELDS),
        team_check="resolve",
        resource_team_resolver="test_case_section",
        projection=_SECTION_PROJECTION,
        confirmation_action_key="assistant.action.update_test_case_section",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="delete_test_case_section",
        method="DELETE",
        path_template="/api/test-case-sets/{set_id}/sections/{section_id}",
        summary="Permanently delete a section.",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        path_params=("set_id", "section_id"),
        team_check="resolve",
        resource_team_resolver="test_case_section",
        projection=(),
        has_no_response_body=True,
        confirmation_action_key="assistant.action.delete_test_case_section",
        warning_key="assistant.warning.irreversible",
        target_resolver="single",
    ),
]
