"""工具目錄：Test Run Configs/Items（4.1–4.19）與 Test Run Sets/Automation（5.1–5.14）。"""

from __future__ import annotations

from app.auth.models import PermissionType
from app.services.assistant.schema_helpers import body, s_array, s_bool, s_int, s_str
from app.services.assistant.tool_registry import (
    HIGH_IMPACT,
    IDEMPOTENT_WRITE,
    IRREVERSIBLE,
    READ,
    REVERSIBLE_WRITE,
    AssistantTool,
)

_TRC_PROJECTION = (
    "id", "name", "description", "set_id", "set_name", "test_case_set_ids", "test_version",
    "test_environment", "build_number", "related_tp_tickets", "status", "start_date", "end_date",
    "total_test_cases", "executed_cases", "passed_cases", "failed_cases", "created_at", "updated_at",
)
_ITEM_PROJECTION = (
    "id", "config_id", "test_case_number", "title", "priority", "test_result", "assignee_name",
    "executed_at", "execution_duration", "attachment_count", "execution_result_count", "comment",
    "created_at", "updated_at",
)
_TRS_PROJECTION = (
    "id", "name", "description", "status", "archived_at", "related_tp_tickets", "created_at", "updated_at",
    "test_run_count", "automation_covered_case_count", "test_runs",
)
_RUN_PROJECTION = (
    "id", "test_run_set_id", "script_group_id", "script_group_name", "status", "triggered_by",
    "branch", "environment", "report_url", "started_at", "finished_at", "duration_ms",
    "error_summary", "created_at", "updated_at",
)

TOOLS = [
    # ---- 4. Test Run Configs / Items ----
    AssistantTool(
        name="list_test_runs",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-configs/",
        summary="List test run configs in the current team.",
        permission=PermissionType.READ,
        risk_level=READ,
        query_params={"status_filter": s_str("draft|active|completed|archived")},
        team_check="inject",
        projection=_TRC_PROJECTION + ("_deep_links",),
    ),
    AssistantTool(
        name="get_test_run",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}",
        summary="Get a test run config's detail.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("config_id",),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=_TRC_PROJECTION + ("_deep_links",),
    ),
    AssistantTool(
        name="create_test_run_config",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-configs/",
        summary="Create a new test run config.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        body_schema=body(
            {
                "name": s_str(),
                "description": s_str(),
                "test_version": s_str(),
                "test_environment": s_str(),
                "build_number": s_str(),
                "test_case_set_ids": s_array(s_int()),
            },
            required=["name"],
        ),
        team_check="resolve",
        resource_team_resolver="create_test_run_config_scope",
        projection=_TRC_PROJECTION + ("_deep_links",),
        confirmation_action_key="assistant.action.create_test_run_config",
        warning_key="assistant.warning.confirm_write",
        target_resolver="create",
    ),
    AssistantTool(
        name="update_test_run_config",
        method="PUT",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}",
        summary="Update a test run config's descriptive fields (not status or scope).",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,
        path_params=("config_id",),
        body_schema=body(
            {"name": s_str(), "description": s_str(), "test_version": s_str(), "test_environment": s_str(), "build_number": s_str()}
        ),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=_TRC_PROJECTION,
        confirmation_action_key="assistant.action.update_test_run_config",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="set_test_run_status",
        method="PUT",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/status",
        summary=(
            "Transition a test run config's status. Allowed edges: draft→active|archived, "
            "active→completed|archived, completed→archived, archived→active|draft. "
            "Main-path multi-hop: draft→completed is applied as draft→active→completed in one call. "
            "Use archive_test_run for archived. Prefer status=completed after results are saved."
        ),
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        path_params=("config_id",),
        body_schema=body({"status": s_str("draft|active|completed", enum=["draft", "active", "completed"])}, required=["status"]),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=_TRC_PROJECTION,
        confirmation_action_key="assistant.action.set_test_run_status",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="archive_test_run",
        method="PUT",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/status",
        summary="Archive a test run config (safe, reversible; never uses DELETE).",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("config_id",),
        fixed_body={"status": "archived"},
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=_TRC_PROJECTION,
        confirmation_action_key="assistant.action.archive_test_run",
        warning_key="assistant.warning.high_impact",
        target_resolver="single",
    ),
    AssistantTool(
        name="delete_test_run_config",
        method="DELETE",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}",
        summary="Permanently delete a test run config and its items.",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        path_params=("config_id",),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=(),
        has_no_response_body=True,
        confirmation_action_key="assistant.action.delete_test_run_config",
        warning_key="assistant.warning.irreversible",
        target_resolver="single",
    ),
    AssistantTool(
        name="restart_test_run",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/restart",
        summary=(
            "Create a NEW test run config by copying items from a source run "
            "(mode=all|failed|pending). New run starts as active. If the source belongs "
            "to a Test Run Set, the new run is attached to the same set. "
            "Does not mutate the source run's status or items. Report new_config_id after confirm."
        ),
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("config_id",),
        body_schema=body(
            {"mode": s_str("all|failed|pending", enum=["all", "failed", "pending"]), "name": s_str()},
            required=["mode"],
        ),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=("success", "mode", "new_config_id", "created_count", "set_id", "_deep_links"),
        confirmation_action_key="assistant.action.restart_test_run",
        warning_key="assistant.warning.high_impact",
        target_resolver="single",
    ),
    AssistantTool(
        name="list_test_run_items",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/",
        summary=(
            "List full items in a test run. Prefer list_test_run_item_refs for bulk assign/"
            "result updates; keep limit small."
        ),
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("config_id",),
        query_params={
            "search": s_str(),
            "test_result_filter": s_str(),
            "executed_only": s_bool(),
            "sort_by": s_str(),
            "sort_order": s_str(enum=["asc", "desc"]),
            "skip": s_int(),
            "limit": s_int(),
        },
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=_ITEM_PROJECTION + ("_deep_links",),
        default_limit=50,
        max_limit=100,
    ),
    AssistantTool(
        name="list_test_run_item_refs",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/refs",
        summary=(
            "List slim item refs (id, test_case_number, test_result, assignee_name) for a run. "
            "Prefer this before full list_test_run_items when batch-updating assignee/result."
        ),
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("config_id",),
        query_params={
            "search": s_str(),
            "test_result_filter": s_str("use null/pending for unexecuted"),
            "executed_only": s_bool(),
            "skip": s_int(),
            "limit": s_int("page size, max 500"),
        },
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=("id", "test_case_number", "test_result", "assignee_name"),
        default_limit=100,
        max_limit=500,
    ),
    AssistantTool(
        name="add_test_run_items",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/",
        summary="Add test cases (by number) to a test run.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("config_id",),
        body_schema=body(
            {"items": s_array(body({"test_case_number": s_str()}, required=["test_case_number"]))},
            required=["items"],
        ),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=("created_count", "skipped_duplicates", "errors"),
        confirmation_action_key="assistant.action.add_test_run_items",
        warning_key="assistant.warning.high_impact",
        target_resolver="batch",
    ),
    AssistantTool(
        name="update_test_run_item",
        method="PUT",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/{item_id}",
        summary="Update a single test run item's assignee or metadata (not the result; use batch_update_results).",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,
        path_params=("config_id", "item_id"),
        body_schema=body({"assignee_name": s_str()}),
        team_check="resolve",
        resource_team_resolver="test_run_item",
        projection=_ITEM_PROJECTION,
        confirmation_action_key="assistant.action.update_test_run_item",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="batch_update_results",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/batch-update-results",
        summary=(
            "Batch-update multiple run items in one call: test_result and/or assignee_name and/or comment. "
            "Prefer this over looping update_test_run_item. Assignee-only updates are allowed "
            "(omit test_result when only reassigning)."
        ),
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("config_id",),
        body_schema=body(
            {
                "updates": s_array(
                    body(
                        {
                            "id": s_int(),
                            "test_result": s_str("pass|fail|blocked|skipped", enum=["pass", "fail", "blocked", "skipped"]),
                            "assignee_name": s_str("assignee display name; omit test_result for assign-only updates"),
                            "comment": s_str(),
                        },
                        required=["id"],
                    )
                )
            },
            required=["updates"],
        ),
        team_check="resolve",
        resource_team_resolver="batch_test_run_items_same_config",
        projection=("processed_count", "success_count", "success", "error_count", "error_messages"),
        confirmation_action_key="assistant.action.batch_update_results",
        warning_key="assistant.warning.high_impact",
        target_resolver="batch",
    ),
    AssistantTool(
        name="batch_update_test_run_items_by_filter",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/batch-update-by-filter",
        summary=(
            "Batch-update run items matching a server-side filter (assignee_unassigned, test_result, "
            "search). Server resolves matches (max 500); prefer over full list + batch_update_results."
        ),
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("config_id",),
        body_schema=body(
            {
                "filter": body(
                    {
                        "test_result": s_str(
                            "pass|fail|blocked|skipped|null|pending (null/pending = unexecuted)",
                            enum=["pass", "fail", "blocked", "skipped", "null", "pending"],
                        ),
                        "assignee_unassigned": s_bool("true = empty/null assignee only"),
                        "assignee_name": s_str("exact assignee name; mutually exclusive with assignee_unassigned"),
                        "search": s_str("title/number search"),
                    }
                ),
                "patch": body(
                    {
                        "assignee_name": s_str(),
                        "test_result": s_str(
                            "pass|fail|blocked|skipped",
                            enum=["pass", "fail", "blocked", "skipped"],
                        ),
                    }
                ),
            },
            required=["patch"],
        ),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=(
            "processed_count",
            "success_count",
            "success",
            "error_count",
            "error_messages",
            "matched_count",
            "matched_ids",
        ),
        confirmation_action_key="assistant.action.batch_update_test_run_items_by_filter",
        warning_key="assistant.warning.high_impact",
        target_resolver="filter_batch",
    ),
    AssistantTool(
        name="delete_test_run_item",
        method="DELETE",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/{item_id}",
        summary="Remove a single item from a test run.",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        path_params=("config_id", "item_id"),
        team_check="resolve",
        resource_team_resolver="test_run_item",
        projection=(),
        has_no_response_body=True,
        confirmation_action_key="assistant.action.delete_test_run_item",
        warning_key="assistant.warning.irreversible",
        target_resolver="single",
    ),
    AssistantTool(
        name="upload_run_item_results",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/{item_id}/upload-results",
        summary="Upload a chat-provided file as a run item's execution result evidence.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        path_params=("config_id", "item_id"),
        multipart_file_param="files",
        team_check="resolve",
        resource_team_resolver="test_run_item",
        projection=("uploaded_files",),
        confirmation_action_key="assistant.action.upload_run_item_results",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="get_run_statistics",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/statistics",
        summary="Get pass/fail/execution statistics for a test run.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("config_id",),
        team_check="resolve",
        resource_team_resolver="test_run_config",
        projection=("total_test_cases", "executed_cases", "passed_cases", "failed_cases", "execution_rate", "pass_rate"),
    ),
    AssistantTool(
        name="list_item_bug_tickets",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/{item_id}/bug-tickets",
        summary="List JIRA bug tickets linked to a run item.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("config_id", "item_id"),
        team_check="resolve",
        resource_team_resolver="test_run_item",
        projection=("ticket_number",),
    ),
    AssistantTool(
        name="add_item_bug_ticket",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/{item_id}/bug-tickets",
        summary="Link a JIRA bug ticket to a run item.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        path_params=("config_id", "item_id"),
        body_schema=body({"ticket_number": s_str()}, required=["ticket_number"]),
        team_check="resolve",
        resource_team_resolver="test_run_item",
        projection=("ticket_number",),
        confirmation_action_key="assistant.action.add_item_bug_ticket",
        warning_key="assistant.warning.confirm_write",
        target_resolver="create",
    ),
    AssistantTool(
        name="remove_item_bug_ticket",
        method="DELETE",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}/items/{item_id}/bug-tickets/{ticket_number:path}",
        summary="Unlink a JIRA bug ticket from a run item. Fully recoverable via add_item_bug_ticket.",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,  # DELETE 豁免：見 tool-matrix「DELETE 豁免」
        path_params=("config_id", "item_id", "ticket_number"),
        path_param_schemas={"ticket_number": s_str("JIRA ticket number，例如 PRJ-123")},
        team_check="resolve",
        resource_team_resolver="test_run_item",
        projection=(),
        has_no_response_body=True,
        confirmation_action_key="assistant.action.remove_item_bug_ticket",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="update_test_run_scope",
        method="PUT",
        path_template="/api/teams/{team_id}/test-run-configs/{config_id}",
        summary="Change which test-case-sets a test run's scope covers.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("config_id",),
        body_schema=body({"test_case_set_ids": s_array(s_int())}, required=["test_case_set_ids"]),
        team_check="resolve",
        resource_team_resolver="update_test_run_scope",
        projection=_TRC_PROJECTION + ("cleanup_summary",),
        confirmation_action_key="assistant.action.update_test_run_scope",
        warning_key="assistant.warning.high_impact",
        target_resolver="single",
    ),
    # ---- 5. Test Run Sets / Automation ----
    AssistantTool(
        name="list_test_run_sets",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-sets/",
        summary="List test run sets in the current team.",
        permission=PermissionType.READ,
        risk_level=READ,
        query_params={"include_archived": s_bool()},
        team_check="inject",
        projection=_TRS_PROJECTION + ("_deep_links",),
    ),
    AssistantTool(
        name="get_test_run_set",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}",
        summary="Get a test run set with its member runs.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("set_id",),
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=_TRS_PROJECTION + ("_deep_links",),
    ),
    AssistantTool(
        name="create_test_run_set",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/",
        summary="Create a new test run set.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        body_schema=body({"name": s_str(), "description": s_str()}, required=["name"]),
        team_check="inject",
        projection=_TRS_PROJECTION + ("_deep_links",),
        confirmation_action_key="assistant.action.create_test_run_set",
        warning_key="assistant.warning.confirm_write",
        target_resolver="create",
    ),
    AssistantTool(
        name="update_test_run_set",
        method="PUT",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}",
        summary="Update a test run set's name/description (not status).",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,
        path_params=("set_id",),
        body_schema=body({"name": s_str(), "description": s_str()}),
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=_TRS_PROJECTION,
        confirmation_action_key="assistant.action.update_test_run_set",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="archive_test_run_set",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/archive",
        summary="Archive a test run set (safe, reversible; never uses DELETE).",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("set_id",),
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=_TRS_PROJECTION,
        confirmation_action_key="assistant.action.archive_test_run_set",
        warning_key="assistant.warning.high_impact",
        target_resolver="single",
    ),
    AssistantTool(
        name="delete_test_run_set",
        method="DELETE",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}",
        summary="Permanently delete a test run set and its member configs/files.",
        permission=PermissionType.WRITE,
        risk_level=IRREVERSIBLE,
        path_params=("set_id",),
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=(),
        has_no_response_body=True,
        confirmation_action_key="assistant.action.delete_test_run_set",
        warning_key="assistant.warning.irreversible",
        target_resolver="single",
    ),
    AssistantTool(
        name="add_runs_to_set",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/members",
        summary="Attach existing test run configs to a test run set.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        path_params=("set_id",),
        body_schema=body({"config_ids": s_array(s_int())}, required=["config_ids"]),
        team_check="resolve",
        resource_team_resolver="add_runs_to_set",
        projection=_TRS_PROJECTION,
        confirmation_action_key="assistant.action.add_runs_to_set",
        warning_key="assistant.warning.confirm_write",
        target_resolver="membership",
    ),
    AssistantTool(
        name="move_run_between_sets",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/members/{config_id}/move",
        summary="Move (or detach) a test run config between test run sets.",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,
        path_params=("config_id",),
        body_schema=body({"target_set_id": s_int()}),
        team_check="resolve",
        resource_team_resolver="move_run_between_sets",
        projection=_TRC_PROJECTION,
        confirmation_action_key="assistant.action.move_run_between_sets",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="generate_run_set_report",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/generate-html",
        summary="Generate (or regenerate) an HTML report for a test run set.",
        permission=PermissionType.WRITE,
        risk_level=REVERSIBLE_WRITE,
        path_params=("set_id",),
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=("report_id", "report_url"),
        confirmation_action_key="assistant.action.generate_run_set_report",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
    AssistantTool(
        name="get_run_set_report",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/report",
        summary="Check whether a test run set's HTML report exists.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("set_id",),
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=("exists", "report_url"),
    ),
    AssistantTool(
        name="list_automation_runs",
        method="GET",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/runs",
        summary="List automation CI runs associated with a test run set.",
        permission=PermissionType.READ,
        risk_level=READ,
        path_params=("set_id",),
        query_params={
            "status": s_str(),
            "branch": s_str(),
            "environment": s_str(),
            "cursor": s_str(),
            "limit": s_int(),
        },
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=_RUN_PROJECTION,
    ),
    AssistantTool(
        name="run_automation",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/run-automation",
        summary="Trigger CI automation execution for a test run set.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("set_id",),
        body_schema=body({"suite_id": s_int(), "environment": s_str()}),
        team_check="resolve",
        resource_team_resolver="test_run_set",
        projection=("triggered_suite_ids", "run_ids"),
        confirmation_action_key="assistant.action.run_automation",
        warning_key="assistant.warning.high_impact",
        target_resolver="single",
    ),
    AssistantTool(
        name="cancel_automation_run",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/runs/{run_id}/cancel",
        summary="Cancel an in-progress CI automation run.",
        permission=PermissionType.WRITE,
        risk_level=HIGH_IMPACT,
        path_params=("set_id", "run_id"),
        team_check="resolve",
        resource_team_resolver="automation_run",
        projection=_RUN_PROJECTION,
        confirmation_action_key="assistant.action.cancel_automation_run",
        warning_key="assistant.warning.high_impact",
        target_resolver="single",
    ),
    AssistantTool(
        name="reconcile_automation_run",
        method="POST",
        path_template="/api/teams/{team_id}/test-run-sets/{set_id}/runs/{run_id}/reconcile",
        summary="Re-sync (idempotent) an automation run's status against the external CI system.",
        permission=PermissionType.WRITE,
        risk_level=IDEMPOTENT_WRITE,
        path_params=("set_id", "run_id"),
        body_schema=body({"external_run_id": s_str()}),
        team_check="resolve",
        resource_team_resolver="automation_run",
        projection=_RUN_PROJECTION,
        confirmation_action_key="assistant.action.reconcile_automation_run",
        warning_key="assistant.warning.confirm_write",
        target_resolver="single",
    ),
]
